MP.Ruleset({
	key = "badlatro",
	multiplayer_content = true,
	banned_jokers = {
		"j_caino",
		"j_perkeo",
		"j_triboulet",
		"j_yorick",
		"j_blueprint",
		"j_ancient",
		"j_baron",
		"j_baseball",
		"j_dna",
		"j_family",
		"j_trio",
		"j_vagabond",
		"j_acrobat",
		"j_card_sharp",
		"j_cartomancer",
		"j_certificate",
		"j_dusk",
		"j_fibonacci",
		"j_hologram",
		"j_loyalty_card",
		"j_lucky_cat",
		"j_midas_mask",
		"j_bloodstone",
		"j_arrowhead",
		"j_onyx_agate",
		"j_selzer",
		"j_trading",
		"j_abstract",
		"j_blue_joker",
		"j_cavendish",
		"j_photograph",
		"j_hanging_chad",
		"j_mail",
		"j_brainstorm",
		"j_mime",
		"j_steel_joker",
		"j_reserved_parking",
		"j_mp_defensive_joker",
	},
	banned_consumables = {
		"c_justice",
		"c_deja_vu",
		"c_trance",
	},
	banned_vouchers = {
		"v_magic_trick",
	},
	banned_enhancements = {
		"m_glass",
	},
	banned_tags = {
		"tag_uncommon",
		"tag_meteor",
		"tag_garbage",
		"tag_top_up",
		"tag_handy",
	},
	banned_blinds = {},
	reworked_jokers = {},
	reworked_consumables = {},
	reworked_vouchers = {},
	reworked_enhancements = {},
	reworked_tags = {},
	reworked_blinds = {},
	create_info_menu = function()
		return MP.UI.CreateRulesetInfoMenu({
			multiplayer_content = true,
			forced_lobby_options = false,
			description_key = "k_badlatro_description",
		})
	end,
}):inject()
