-- Localization by @ninoleplot - Localisation par @ninoleplot
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "CASSÉ",
				text = {
					"Cette carte est cassée, ou n'est",
					"pas implémentée dans une version",
					"actuelle d'un mod que vous utilisez.",
				},
			},
			j_mp_defensive_joker = {
				name = "Joker Défensif",
				text = {
					"{C:chips}+#1#{} Jetons par {C:red,E:1}vie{}",
					"de moins que votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Actuellement {C:chips}+#2#{C:inactive} Jetons)",
				},
			},
			j_mp_skip_off = {
				name = "Marelle",
				text = {
					"{C:blue}+#1#{} Mains et {C:red}+#2#{} Défausses",
					"par {C:attention}Blinde{} passée ",
					"{C:attention}de plus{} que votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Actuellement {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Machine à Sous",
				text = {
					"{C:green}#1# chance(s) sur #2#{} d'octroyer",
					"{X:mult,C:white}X#3#{} Multi et {C:money}$#4#{}",
					"{C:green}#5# chance(s) sur #6#{} de donner",
					"{C:money}$#7#{} à votre {X:purple,C:white}Némésis{}",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Si vous atteignez une {C:attention}Blinde PvP",
					"avant votre {X:purple,C:white}Némésis{},",
					"crée une carte {C:spectral}Spectrale{} aléatoire",
					"{C:inactive}(Selon la place disponible)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Joker Conjoint",
				text = {
					"Pendant une {C:attention}Blinde PvP{}, octroie",
					"{X:mult,C:white}X#1#{} Multi pour chaque {C:blue}Main{}",
					"restante de votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Max. {X:mult,C:white}X#2#{C:inactive} Multi, Actuellement {X:mult,C:white}X#3#{C:inactive} Multi)",
				},
			},
			j_mp_penny_pincher = {
				name = "Grippe-Sou",
				text = {
					"A la fin d'une manche, gagnez {C:money}$#1#{}",
					"par {C:money}$#2#{} dépensés par votre{X:purple,C:white}Némésis{}",
					"dans le magasin correspondant de la {C:attention}dernière mise initiale{}",
					"{C:inactive}(Prochain gain: {C:money}$#3#{C:inactive})",
				},
			},
			j_mp_taxes = {
				name = "Impôts",
				text = {
					"{C:mult}+#1#{} Multi pour chaque carte",
					"{C:attention}vendue{} par votre {X:purple,C:white}Némésis{}",
					"durant cette partie, s'actualise quand la",
					" {C:attention}Blinde PvP{} est sélectionnée",
					"{C:inactive}(Actuellement {C:mult}+#2#{C:inactive} Multi,",
					"{C:inactive}prochaine actualisation : {C:mult}+#3#{C:inactive} Multi)",
				},
			},
			j_mp_magnet = {
				name = "Aimant",
				text = {
					"Après {C:attention}#1#{} manches,",
					"vendez cette carte pour {C:attention}Copier{}",
					"le {C:attention}Joker{} à la plus haute ",
					"valeur de vente de votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Actuellement {C:attention}#2#{C:inactive}/#3# manches)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"{C:red}+#1#{} défausse(s) et",
					"{C:red}+#2#{} défausse(s) pour votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Détruit après une {C:attention}Blinde PvP{}{C:inactive})",
				},
			},
			j_mp_pacifist = {
				name = "Pacifiste",
				text = {
					"Octroie {X:mult,C:white}X#1#{} Multi",
					"{C:attention}sauf{} pendant les {C:attention}Blindes PvP{}",
				},
			},
			j_mp_hanging_chad = {
				name = "Carte de Vote",
				text = {
					"Déclenche à nouveau la {C:attention}première{} et la {C:attention}seconde{}",
					"carte jouée pour marquer des points",
					"{C:attention}#1#{} fois supplémentaire(s)",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Astéroïde",
				text = {
					"Retire #1# niveau",
					"à la {C:legendary,E:1}main de poker{}",
					"la plus améliorée",
					"de votre {X:purple,C:white}Némésis{}",
					"au début de la prochaine {C:attention}Blinde PvP{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Votre Némésis",
				text = {
					"Jouez contre un autre joueur,",
					"le plus haut score l'emporte.",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantôme",
				text = {
					"{C:attention}Éternel{} et {C:dark_edition}Négatif{}",
					"Créé et détruit par votre {X:purple,C:white}Némésis{}",
				},
			},
		},
		Enhanced = {
			m_mp_display_glass = {
				name = "Carte Verre",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"{C:green}#2# chance(s) sur #3#{} de",
					"détruire la carte",
				},
			},
			m_mp_sandbox_display_glass = {
				name = "Carte Verre",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"{C:green}#2# chance(s) sur #3#{} de",
					"détruire la carte",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Némésis",
				text = {
					"{X:purple,C:white}#1#{}",
					"Votre seul et unique Némésis.",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Fantôme",
		},
		dictionary = {
			b_singleplayer = "Solo",
			b_join_lobby = "Rejoindre un Lobby",
			b_return_lobby = "Retourner au Lobby",
			b_reconnect = "Se Reconnecter",
			b_create_lobby = "Créer un Lobby",
			b_start_lobby = "Créer le Lobby",
			b_ready = "Prêt",
			b_unready = "Pas Prêt",
			b_leave_lobby = "Quitter le Lobby",
			b_mp_discord = "Serveur Discord Balatro Multiplayer",
			b_start = "COMMENCER",
			b_wait_for_host_start = {
				"EN ATTENTE DE",
				"L'HÔTE POUR COMMENCER",
			},
			b_wait_for_players = {
				"EN ATTENTE DES",
				"JOUEURS",
			},
			b_lobby_options = "OPTIONS DE LOBBY",
			b_copy_clipboard = "Copier vers le presse-papiers",
			b_view_code = "VOIR LE CODE",
			b_copy_code = "COPIER LE CODE",
			b_leave = "PARTIR",
			b_opts_cb_money = "Gagner des $ lors de la perte d'une vie",
			b_opts_no_gold_on_loss = "Ne pas obtenir les récompenses de la Blinde lors d'une défaite",
			b_opts_death_on_loss = "Perdre une vie après une défaite contre une Blinde non-PvP",
			b_opts_start_antes = "Mises initiales de Départ",
			b_opts_diff_seeds = "Graines différentes pour les joueurs",
			b_opts_lives = "Vies",
			b_opts_multiplayer_jokers = "Activer les cartes multijoueur",
			b_opts_player_diff_deck = "Les joueurs peuvent avoir des decks différents",
			b_opts_normal_bosses = "Activer les effets des Blindes Boss",
			b_opts_timer = "Activer le Timer",
			b_reset = "Réinitialiser",
			b_set_custom_seed = "Graine Personnalisée",
			b_mp_kofi_button = "Me soutenir sur Ko-fi",
			b_unstuck = "Se Décoincer",
			b_unstuck_blind = "Coincé en dehors du PvP",
			b_misprint_display = "Afficher la prochaine carte du deck",
			b_players = "Joueurs",
			b_lobby_info = "Infos Lobby",
			b_continue_singleplayer = "Continuer en Solo",
			b_the_order_integration = "Activer l'intégration de The Order",
			b_view_nemesis_deck = "Voir le deck adverse",
			b_toggle_jokers = "Activer/Désactiver les Jokers",
			k_continue_singleplayer_tooltip = "Votre partie en solo sera écrasée",
			k_enemy_score = "Score ennemi actuel",
			k_enemy_hands = "Mains adverses restantes: ",
			k_coming_soon = "Bientôt!",
			k_wait_enemy = "En attente que l'adversaire termine...",
			k_wait_enemy_reach_this_blind = "En attente que l'adversaire atteigne cette blinde...",
			k_lives = "Vies",
			k_lost_life = "A perdu une Vie",
			k_total_lives_lost = " Total de vies perdues ($4 chacune)",
			k_attrition_name = "Érosion",
			k_enter_lobby_code = "Entrer le code du Lobby",
			k_paste = "Coller depuis le presse-papiers",
			k_username = "Pseudo:",
			k_enter_username = "Entrer un pseudo",
			k_join_discord = "Rejoindre le ",
			k_discord_msg = "Vous pourrez y signaler des bugs et trouver des joueurs avec qui jouer",
			k_enter_to_save = "Appuyer sur Entrée pour sauvegarder",
			k_in_lobby = "Dans le Lobby",
			k_connected = "Connecté aux Services",
			k_warn_service = "WARN: Impossible de Trouver le Service Multijoueur",
			k_set_name = "Entrez votre pseudo dans le menu ! (Mods > Cliquer sur le mod Multiplayer > Config)",
			k_mod_hash_warning = "Les joueurs n'ont pas les même mods/versions de mods! Cela peut causer des dysfonctionnements!",
			k_warning_unlock_profile = "Le profil actuel n'a pas tout le contenu débloqué. Si cette partie est classée/un tournoi, veuillez créer un nouveau profil et cliquer sur 'tout débloquer' dans les paramètres du profil.",
			k_warning_nemesis_unlock = "Votre adversaire joue sur un profil qui n'a pas tout débloqué. Indiquez lui d'appuyer sur 'tout débloquer' dans les paramètres de son profil.",
			k_warning_no_order = "Un joueur a activé l'intégration de The Order mais l'autre non. Les graines seront peut-être différentes.",
			k_warning_cheating1 = "Si vous lisez ceci, il se peut que votre adversaire triche.",
			k_warning_cheating2 = "Si cette partie est classée, envoyez le message '%s' et ouvrez un ticket de support dans #support.",
			k_message1 = "Attends, ma mère a fait des mini-pizzas",
			k_message2 = "Bouge pas, faut que j’aille sortir le rôti du four.",
			k_message3 = "Une seconde, c’est ma mère qui m’appelle",
			k_message4 = "Je reviens, mon chat est en feu",
			k_message5 = "Attends, j'ai oublié de fermer le gaz",
			k_message6 = "Attends, mon caillou de compagnie a pris la fuite",
			k_message7 = "Deux secondes, mes plantes réclament de l'eau",
			k_message8 = "Je reviens, mes chaussettes complotent contre moi",
			k_message9 = "Désolé, mon Wi-Fi traverse une crise existentielle",
			k_lobby_options = "Options de Lobby",
			k_connect_player = "Joueurs Connectés:",
			k_opts_only_host = "Seul l'Hôte du Lobby peut changer ces options",
			k_opts_gm = "Options du Mode de Jeu",
			k_opts_pvp_start_round = "Le PvP commence à la mise initiale",
			k_opts_pvp_timer = "Timer",
			k_opts_showdown_starting_antes = "L'Affrontement commence à la Mise Initiale",
			k_opts_pvp_timer_increment = "Incrément du Timer",
			k_bl_life = "Vie",
			k_bl_or = "ou",
			k_bl_death = "Mort",
			k_bl_mostchips = "Le plus de jetons l'emporte",
			k_current_seed = "Graine actuelle: ",
			k_random = "Aléatoire",
			k_standard = "Standard",
			k_standard_description = "Les règles classiques, les cartes Multijoueur sont incluses ainsi que les ajustements du jeu de base pour le multijoueur.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "Les règles du jeu de base, pas de cartes multijoueur, pas de changement du contenu de base.",
			k_weekly = "Hebdo",
			k_weekly_description = "Des règles spéciales qui changent toutes les semaines/deux semaines. Essayez par vous-même! Actuellement: ",
			k_tournament = "Tournoi",
			k_tournament_description = "Règles de tournoi, similaire aux règles standard mais sans les options de lobby.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Des règles hebdomadaires écrites par @dr_monty_the_snek sur le serveur discord, qui ont été ajoutées au mod de façon permanente.",
			k_attrition = "Erosion",
			k_attrition_description = "Toutes les blindes boss sont PvP. Pas le temps de se préparer. Ce mode force à être prêt au combat dès le début.",
			k_showdown = "Confrontation",
			k_showdown_description = "Après les 2 premières mises initiales, toutes les blindes boss sont PvP. Ce mode laisse le temps de se préparer avant le combat.",
			k_survival = "Survie",
			k_survival_description = "Pas de blindes PvP, le joueur allant le plus loin dans la partie gagne. Ce mode permet de tester vos capacités à aller le plus loin possible dans le jeu classique.",
			k_oops_ex = "Oups!",
			k_asteroids = "Astéroïdes",
			k_amount_short = "Qté",
			k_filed_ex = "C'est envoyé !",
			k_timer = "Timer",
			k_mods_list = "Liste des Mods",
			k_enemy_jokers = "Jokers Adverses",
			k_your_jokers = "Vos Jokers",
			k_nemesis_deck = "Deck Adverse",
			k_your_deck = "Votre Deck",
			k_the_order_credit = "*Crédit à @MathIsFun_",
			k_the_order_integration_desc = "La création de carte sera modifiée pour ne pas être basée sur la mise initiale et pour utiliser une seule pool pour chaque type/rareté",
			k_requires_restart = "*Nécessite un redémarrage pour s'appliquer",
			k_bans = "Bans",
			k_reworks = "Ajouts/Refontes",
			ml_enemy_loc = {
				"Position",
				"ennemie",
			},
			ml_mp_kofi_message = {
				"Ce mod et serveur de jeu est",
				"développé et maintenu par ",
				"une seule personne, si",
				"vous l'aimez, n'hésitez pas à",
			},
			ml_lobby_info = {
				"Infos",
				"Lobby",
			},
			loc_ready = "Prêt.e pour le PvP",
			loc_selecting = "Sélectionne une Blinde",
			loc_shop = "Dans le magasin",
			loc_playing = "Joue ",
		},
		v_dictionary = {
			a_mp_art = {
				"Art: #1#",
			},
			a_mp_code = {
				"Code: #1#",
			},
			a_mp_idea = {
				"Idée: #1#",
			},
			a_mp_skips_ahead = {
				"#1# Blindes passées d'avance",
			},
			a_mp_skips_behind = {
				"#1# Blindes passées de retard",
			},
			a_mp_skips_tied = {
				"En Égalité",
			},
			k_banned_objs = "#1# Banni(e)s",
			k_no_banned_objs = "Pas de #1# Banni(e)s",
			k_reworked_objs = "#1# Ajouté(e)s/Modifié(e)s",
			k_no_reworked_objs = "Pas de #1# Ajouté(e)s/Modifié(e)s ",
		},
		v_text = {
			ch_c_hanging_chad_rework = {
				"{C:attention}Carte de Vote{} est {C:dark_edition}modifié",
			},
			ch_c_glass_cards_rework = {
				"{C:attention}Les Cartes Verre{} sont {C:dark_edition}modifiées",
			},
		},
		challenge_names = {
			c_mp_standard = "Standard",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Tournoi",
			c_mp_weekly = "Hebdo",
			c_mp_vanilla = "Vanilla",
			c_mp_misprint_deck = "Deck Erreur d'Impression",
			c_mp_legendaries = "Légendaires",
			c_mp_psychosis = "Psychose",
			c_mp_scratch = "De Zéro",
			c_mp_twin_towers = "Tours Jumelles",
			c_mp_in_the_red = "Dans le Rouge",
			c_mp_paper_money = "Billets de Banque",
			c_mp_high_hand = "Grande Main",
			c_mp_chore_list = "Liste des Corvées",
			c_mp_oops_all_jokers = "Que des Jokers",
			c_mp_divination = "Divination",
			c_mp_skip_off = "La Marelle",
			c_mp_lets_go_gambling = "Le Casino",
			c_mp_speed = "Vitesse",
		},
	},
}
