-- Traduzione creata da @ieatmilk(su discord) e conseguentemente aggiornata da @alexxyo(sempre su discord)
-- Localization by @ieatmilk and updated by @alexxyo
return {
	descriptions = {
		Tag = {
			tag_mp_gambling_sandbox = {
				name = "Patto scommessa",
				text = {
					"{C:green}#1# probabilità su #2#",
					"Che il negozio ha",
					"un {C:red}Jolly raro",
				},
			},
		},
		Joker = {
			j_broken = {
				name = "BROKEN",
				text = {
					"Questa carta non funziona o non è",
					"ancora stata implementata nella versione",
					"attuale di una mod che stai usando.",
				},
			},
			j_mp_defensive_joker = {
				name = "Jolly difensivo",
				text = {
					"Questo {C:attention}Jolly{} guadagna {C:chips}+#1#{} fiche",
					"per ogni {C:red,E:1}vita{} in meno della tua {X:purple,C:white}Nemesi",
					"{C:inactive}(Attualmente {C:chips}+#2#{C:inactive} fiche)",
					"{C:inactive}(Dipende dalla puntata)",
				},
			},
			j_mp_skip_off = {
				name = "Campana",
				text = {
					"{C:blue}+#1#{} Mano e {C:red}+#2#{} Scarto",
					"per ogni {C:attention}buio{} saltato",
					"rispetto alla tua {X:purple,C:white}Nemesi{}",
					"{C:inactive}(Attualmente {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let's go gambling!",
				text = {
					"{C:green}#1# probabilità su #2#{} di ricevere",
					"{X:mult,C:white}X#3#{} Molt e {C:money}$#4#",
					"{C:green}#5# probabilità su #6#{} di dare",
					"{C:money}$#7#{} alla tua {X:purple,C:white}Nemesi{} in un {C:attention}Buio PvP",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Se raggiungi un {C:attention}Buio PvP",
					"prima della tua {X:purple,C:white}Nemesi{}",
					"crea una carta {C:spectral}Spettrale{} a caso",
					"{C:inactive}(Serve spazio)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Jolly congiunto",
				text = {
					"Se in un {C:attention}Buio PvP{}, ottiene",
					"{X:mult,C:white}X#1#{} Molt per ogni {C:blue}Mano{}",
					"rimanente alla tua {X:purple,C:white}Nemesi{}",
					"{C:inactive}(Max {X:mult,C:white}X#2#{C:inactive} Molt, Attualmente {X:mult,C:white}X#3#{C:inactive} Molt)",
				},
			},
			j_mp_penny_pincher = {
				name = "Spilorcio",
				text = {
					"Alla fine del round,",
					"guadagna {C:money}$#1#{} per ogni {C:money}$#2#{} spesi",
					"dalla tua {X:purple,C:white}Nemesi{} nell'ultimo negozio",
				},
			},
			j_mp_taxes = {
				name = "Tasse",
				text = {
					"Quando la tua {X:purple,C:white}Nemesi{} vende",
					"una carta, guadagna {C:mult}+#1#{} Molt.",
					"Si aggiorna quando viene",
					"selezionato il {C:attention}Buio PvP",
					"{C:inactive}(Attualmente {C:mult}+#2#{C:inactive} Molt)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"Alla fine del prossimo {C:attention}Buio PvP",
					"consuma questo {C:attention}Jolly{} per",
					"assegnare {C:red}+#1#{} Scarti a te e ",
					"{C:red}-#2#{} Scarto alla tua {X:purple,C:white}Nemesi{} per questo ante",
				},
			},
			j_mp_pacifist = {
				name = "Pacifista",
				text = {
					"{X:mult,C:white}X#1#{} Molt",
					"fuori da un {C:attention}Buio PvP",
				},
			},
			j_mp_hanging_chad = {
				name = "Scheda non valida",
				text = {
					"Riattiva la {C:attention}prima{} e la {C:attention}seconda",
					"carta giocata per ottenere punti",
					"{C:attention}#1#{} volta in più",
				},
			},
			j_mp_bloodstone = {
				name = "Diaspro sanguinoso",
				text = {
					"{C:green}#1# probabilità su #2#{} che",
					"le carte giocate con",
					"seme {C:hearts}Cuori{} diano",
					"{X:mult,C:white} X#3# {} Molt quando assegna punti",
				},
			},
			j_mp_magnet_sandbox = {
				name = "Magnete",
				text = {
					"Dopo {C:attention}#1#{} round, vendi",
					"questa carta per {C:attention}Copiare{}",
					"il {C:attention}Jolly{} più costoso",
					"della tua {X:purple,C:white}Nemesi",
					"la polarità si inverte dopo {C:attention}#3#{} round",
					"DIVENTANDO UN INUTILE ROTTAME METALLICO!!!!",
					"{C:inactive}(Attualmente {C:attention}#2#{C:inactive}/#1# round)",
				},
			},
			j_mp_cloud_9_sandbox = {
				name = "Nove nuvoloso",
				text = {
					"CONTADINO MONOCOLTURE DI NUMERI",
					"converte il tuo MAZZO DIVERSIFICATO in",
					"PIANTAGIONI DI NOVE REDDITIZI!!!!",
					"{C:inactive}({C:green}#1# probabilità su #2#{}{C:inactive}, attualmente {C:money}$#3#{}{C:inactive})",
				},
			},
			j_mp_lucky_cat_sandbox = {
				name = "Gatto della fortuna",
				text = {
					"OPERATORE DI TUBATURE DA-FORTUNA-A-FRAGILITÀ",
					"il Gatto della fortuna diventa il GATTO DI VETRO",
					"con un POTERE ESPONENZIALE!!!!",
					"{C:inactive}(Attualmente {X:mult,C:white} X#2# {C:inactive}Molt)",
				},
			},
			j_mp_constellation_sandbox = {
				name = "Costellazione",
				text = {
					"disturbo d'ansia da manutenzione del pianeta",
					"DEVI NUTRIRE IL TAMAGOTCHI",
					"o APPASSIRÀ!!!!",
					"{C:inactive}(Attualmente {X:mult,C:white} X#1# {C:inactive}Molt)",
				},
			},
			j_mp_bloodstone_sandbox = {
				name = "Diaspro sanguinoso",
				text = {
					"SINDROME DA REGRESSIONE DELLA PATCH NOTE",
					"tornando al TRAUMA DEL GIORNO DEL LANCIO",
					"per PICCHI DI POTERE NOSTALGICI!!!!",
					"{C:inactive}({C:green}#1# probabilità su #2#{}{C:inactive})",
				},
			},
			j_mp_juggler_sandbox = {
				name = "Giocoliere",
				text = {
					"PERFEZIONISTA DELLA DIMENSIONE DELLA MANO",
					"che deve tenere TUTTE LE CARTE",
					"in aria COSTANTEMENTE!!!!",
					"{C:inactive}(Attualmente {C:attention}+#1#{C:inactive} carte della mano)",
				},
			},
			j_mp_mail_sandbox = {
				name = "Offerta per posta",
				text = {
					"MODULO D'OFFERTA BLOCCATO PER VALORE",
					"qualcuno ha scritto {C:attention}#2#{}",
					"con l'INCHIOSTRO INDELEBILE!!!!",
				},
			},
			j_mp_hit_the_road_sandbox = {
				name = "In viaggio",
				text = {
					"SMALTIMENTO JACK AUTOSTRADALI",
					"lanciando dei {C:attention}Jack{}",
					"NELL'ASFALTO PER SEMPRE!!!!",
					"{C:inactive}(Attualmente {X:mult,C:white} X#2# {C:inactive} Molt)",
				},
			},
			j_mp_misprint_sandbox = {
				name = "Errore di stampa",
				text = {
					"LOTTERIA DI SCHRODINGER, i biglietti del",
					"GIOCATORE sono sia VINCENTI che PERDENTI",
					"finche osservati!!!!",
					"{C:inactive}({V:1}#1#{C:inactive} Molt)",
				},
			},
			j_mp_castle_sandbox = {
				name = "Castello",
				text = {
					"MATRIMONIO DI SEME BASATO SULLO SCARTO",
					"butta via SOLO {V:1}#1#{} per sempre",
					"perché QUESTO È IL LORO LINGUAGGIO D'AMORE!!!!",
					"{C:inactive}(Attualmente {C:chips}+#2#{C:inactive} Fiche)",
				},
			},
			j_mp_runner_sandbox = {
				name = "Corridore",
				text = {
					"SUPREMATISTA DELLE SEQUENZIALI",
					"che crede che TUTTE le altre",
					"MANI DI POKER sono INFERIORI!!!!",
					"{C:inactive}(Attualmente {C:chips}+#1#{C:inactive} Fiche)",
				},
			},
			j_mp_order_sandbox = {
				name = "L'ordine",
				text = {
					"COORDINATORE DELLA RIVOLTA CONTADINA",
					"organizzando i NUMERI per rovesciare",
					"i loro OPPRESSORI FIGURE!!!!",
				},
			},
			j_mp_photograph_sandbox = {
				name = "Fotografia",
				text = {
					"FOTOGRAFO DALLO SCATTO SINGOLO che prende",
					"UNA FOTO PERFETTA PER MANO!!!!",
				},
			},
			j_mp_ride_the_bus_sandbox = {
				name = "Giro sull'autobus",
				text = {
					"PROGRAMMA DI SOBRIETÀ PER LE FIGURE",
					"UNA FIGURA e sei",
					"FUORI DAL BUS!!!!",
					"{C:inactive}(Attualmente {C:mult}+#1#{C:inactive} Molt)",
				},
			},
			j_mp_loyalty_card_sandbox = {
				name = "Carta fedeltà",
				text = {
					"PROGRAMMA FEDELTÀ PER TIPO DI MANO",
					"tradisci {C:attention}#1#{}",
					"e il contatore SI RESETTA!!!!",
					"{C:inactive}(Fedele per {C:attention}#2#/#3#{} {C:inactive}mani)",
				},
			},
			j_mp_faceless_sandbox = {
				name = "Jolly senza volto",
				text = {
					"SOMMELIER D'ELITE DELLE FIGURE",
					"che cura l'artigianato",
					"DEGUSTAZIONE A TRE VARIETÀ",
					"per un ESPERIENZA DI SCARTO PREMIUM!!!!",
				},
			},
			j_mp_square_sandbox = {
				name = "Jolly squadrato",
				text = {
					"PERFEZIONISTA DELLE QUATTRO CARTE",
					"che venera LA SACRA GEOMETRIA DEGLI",
					"ARRANGIAMENTI PERFETTAMENTE BILANCIATI DEL QUADRATO!!!!",
					"{C:inactive}(Attualmente {C:chips}+#1#{C:inactive} Fiche)",
				},
			},
			j_mp_throwback_sandbox = {
				name = "Tuffo nel passato",
				text = {
					"SERVIZI DI CONSULENZA PROFESSIONALE DA CODARDI",
					"io vengo PAGATO per scappare dalle cose",
					"E PIÙ SCAPPO PIÙ DIVENTO FORTE!!!!",
					"{C:inactive}(Attualmente {X:mult,C:white} X#1# {C:inactive} Molt)",
				},
			},
			j_mp_vampire_sandbox = {
				name = "Vampiro",
				text = {
					"vampiro economista CREA",
					"VALUTA BASATA SUI SASSI",
					"DALLA FORZA VITALE!!!!",
					"{C:inactive}(Attualmente {X:mult,C:white} X#2# {C:inactive} Molt)",
				},
			},
			j_mp_baseball_sandbox = {
				name = "Carta da baseball",
				text = {
					'LA "CONTROVERSIA" DELLE CARTE SPORTIVE',
					"travestita da CAMBIO DI BILANCIO!!!!",
				},
			},
			j_mp_steel_joker_sandbox = {
				name = "Jolly d'acciaio",
				text = {
					"SPECIALISTA IN RINDONDANZA DELL'ACCIAIO",
					"ogni LEGA GIOCATA viene",
					"RICONTROLLATA!!!!",
				},
			},
			j_mp_satellite_sandbox = {
				name = "Satellite",
				text = {
					"ansia cronica da degredo del satellite",
					"L'INFRASTRUTTURA CASCA A PEZZI LENTAMENTE",
					"SENZA COSTANTI MIGLIORAMENTI PLANETARI!!!!",
					"{C:inactive}(Attualmente {C:money}$#1#{C:inactive})",
				},
			},
			j_mp_error_sandbox = {
				name = "????",
				text = {
					"PREVIEW DISABLED",
					"{X:purple,C:white,s:0.85}something's{} {X:purple,C:white,s:0.85}wrong",
					"PREVIEW DISABLED",
					"PREVIEW DISABLED",
					-- "{C:inactive}(CURRENTLY {C:money}$7{C:inactive})",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroide",
				text = {
					"Rimuove #1# livello",
					"dalla {C:legendary,E:1}mano di poker{}",
					"di livello più alto della tua",
					"{X:purple,C:white}Nemesi{} all'inizio del {C:attention}Buio PVP{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "La tua Nemesi",
				text = {
					"Sei contro un altro giocatore,",
					"chi fa più punti vince",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantasma",
				text = {
					"{C:attention}Eterna{} e {C:dark_edition}Negativa{}",
					"Creata e distrutta dalla tua {X:purple,C:white}Nemesi{}",
				},
			},
		},
		Enhanced = {
			m_mp_display_glass = {
				name = "Carta di vetro",
				text = {
					"{X:mult,C:white} X#1#{} Molt",
					"{C:green}#2# probabilità su #3#{} di",
					"distruggere la carta",
				},
			},
			m_mp_sandbox_display_glass = {
				name = "Carta di vetro",
				text = {
					"{X:mult,C:white} X#1#{} Molt",
					"{C:green}#2# probabilità su #3#{} di",
					"distruggere la carta",
				},
			},
		},
		Back = {
			b_mp_cocktail = {
				name = "Mazzo cocktail",
				text = {
					"Copia tutti gli effetti",
					"di {C:attention}3{} mazzi",
					"a caso",
				},
			},
			b_mp_gradient = {
				name = "Mazzo gradiente",
				text = {
					"Le carte sono considerate",
					"di un valore più {C:attention}alto{} o più {C:attention}basso",
					"per ogni effetto dei {C:attention}Jolly{}",
				},
			},
			b_mp_indigo = {
				name = "Mazzo indigo",
				text = {
					"Scegli {C:attention}1{} carta extra",
					"da ogni busta di espansione",
				},
			},
			b_mp_orange = {
				name = "Mazzo arancione",
				text = {
					"Inizi con una",
					"{C:attention,T:p_mp_standard_giga}Busta standard giga{}, e",
					"{C:attention}2{} copie de {C:tarot,T:c_hanged_man}Il matto",
				},
			},
			b_mp_oracle = {
				name = "Mazzo dell'oracolo",
				text = {
					"Inizi con {C:spectral,T:c_medium}Medium",
					"e {C:attention,T:v_clearance_sale}Svendita.",
					"I soldi sono limitati",
					"a {C:money}$50",
				},
			},
			b_mp_violet = {
				name = "Mazzo violetto",
				text = {
					"{C:attention}+1{} Buono nel negozio.",
					"Durante l'Ante {C:attention}1{}, i Buoni",
					"hanno uno sconto del {C:attention}50%{}",
				},
			},
			b_mp_heidelberg = {
				name = "Mazzo Heidelberg",
				text = {
					"Crea una copia {C:dark_edition}Negativa{} di",
					"{C:attention}1{} carta {C:attention}consumabile",
					"casuale in tuo possesso",
					"alla fine del {C:attention}negozio",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Nemesi",
				text = {
					"{X:purple,C:white}#1#{}",
					"La tua sola e unica Nemesi",
				},
			},
			p_mp_standard_giga = {
				name = "Busta standard giga",
				text = {
					"Scegli {C:attention}#1#{} tra massimo",
					"{C:attention}#2#{} carte da {C:attention}gioco{} da",
					"aggiungere al tuo mazzo",
					"{C:attention}Non si può saltare{}",
				},
			},
		},
		Stake = {
			stake_mp_planet = {
				name = "Puntata pianeta",
				text = {
					"il fratello più figo della {C:attention}Puntata arancione{}",
					"che ti ha gentilmente reso il tuo {C:red}scarto",
					"{C:red}come supporto emotivo{} perché non è così crudele",
				},
			},
			stake_mp_spectral = {
				name = "Puntata spettrale",
				text = {
					"Si applica alla {C:planet}Puntata pianeta{} e in più:",
					"i Jolly {C:money}A noleggio{} appaiono nel negozio",
					"Richiede scale di punteggio, più veloce per ogni {C:attention}Ante",
				},
			},
			stake_mp_spectralplus = {
				name = "Puntata spettrale+",
				text = {
					"Si applica alla {C:planet}Puntata spettrale{} e in più:",
					"Richiede scale di punteggio",
					"ancora più veloce per ogni {C:attention}Ante",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Fantasma",
		},
		dictionary = {
			b_singleplayer = "Giocatore singolo",
			b_join_lobby = "Unisciti ad una Lobby",
			b_join_lobby_clipboard = "Unisciti dagli appunti",
			b_return_lobby = "Ritorna alla Lobby",
			b_reconnect = "Riconnettiti",
			b_create_lobby = "Crea una Lobby",
			b_start_lobby = "Start Lobby",
			b_ready = "Pronto",
			b_unready = "Non pronto",
			b_leave_lobby = "Lascia Lobby",
			b_mp_discord = "Server Discord di Balatro Multiplayer",
			b_start = "START",
			b_wait_for_host_start = {
				"IN ATTESA",
				"DELL'HOST",
			},
			b_wait_for_players = {
				"IN ATTESA",
				"DI GIOCATORI",
			},
			b_wait_for_guest_ready = {
				"IN ATTESA",
				"DEGLI OSPITI",
			},
			b_lobby_options = "OPZIONI LOBBY",
			b_copy_clipboard = "Copia negli Appunti",
			b_view_code = "RIVELA IL CODICE",
			b_copy_code = "COPIA IL CODICE",
			b_leave = "ESCI",
			b_opts_cb_money = "Rimborsa 4$ per vita persa alla fine di ogni round",
			b_opts_no_gold_on_loss = "Non dare i $ del buio se perdi il round",
			b_opts_death_on_loss = "Perdi una vita in un round non PvP",
			b_opts_start_antes = "Anti iniziali",
			b_opts_diff_seeds = "I giocatori giocano in seed differenti",
			b_opts_lives = "Vite",
			b_opts_multiplayer_jokers = "Abilita carte multigiocatore",
			b_opts_player_diff_deck = "I giocatori hanno mazzi diversi",
			b_opts_normal_bosses = "Attiva l'effetto del buio Boss nei round PvP",
			b_opts_timer = "Abilita Timer",
			b_opts_disable_preview = "Disabilita l'anteprima del punteggio",
			b_opts_the_order = 'Abilita il Jolly "L\'ordine"',
			b_opts_legacy_smallworld = "Meccaniche legacy per Small World",
			b_reset = "Reset",
			b_set_custom_seed = "Imposta seed specifico",
			b_mp_kofi_button = "supporta il creatore su Ko-fi",
			b_unstuck = "Premi se sei bloccato",
			b_unstuck_blind = "Bloccato in PvP esterno",
			b_misprint_display = "Mostra la prossima carta nel mazzo",
			b_players = "Giocatori",
			b_lobby_info = "Info Lobby",
			b_continue_singleplayer = "Continua in Giocatore singolo",
			b_the_order_integration = 'Abilita il Jolly "L\'ordine"',
			b_preview_integration = "Abilita l'anteprima del punteggio",
			b_view_nemesis_deck = "Guarda mazzo",
			b_toggle_jokers = "Mostra Jolly Nemesi",
			b_skip_tutorial = "Salta Tutorial",
			k_yes = "Sì",
			k_no = "No",
			k_are_you_sure = "Sei sicuro?",
			k_has_multiplayer_content = "Contenuto Multiplayer",
			k_forces_lobby_options = "Opzioni fisse",
			k_forces_gamemode = "Modalità forzata",
			k_values_are_modifiable = "* I valori sono modificabili",
			k_rulesets = "Regole",
			k_gamemodes = "Modalità",
			k_competitive = "Competitive",
			k_other = "Varie",
			k_battle = "Battaglia",
			k_challenge = "Sfide",
			k_info = "Descrizione",
			k_continue_singleplayer_tooltip = "Questo sovrascriverà la tua attuale partita in Giocatore singolo",
			k_enemy_score = "Punteggio del Nemico",
			k_enemy_hands = "Mani rimanenti del Nemico: ",
			k_coming_soon = "In Arrivo!",
			k_wait_enemy = "Attendi che il nemico finisca...",
			k_wait_enemy_reach_this_blind = "Attendi che il nemico arrivi a questo buio...",
			k_lives = "Vite",
			k_lost_life = "Hai perso una vita",
			k_total_lives_lost = " Vite perse in totale ($4 ciascuna)",
			k_attrition_name = "Logoramento",
			k_enter_lobby_code = "Inserisci codice Lobby",
			k_paste = "Incolla dagli Appunti",
			k_username = "Nome utente:",
			k_enter_username = "Inserisci Nome utente",
			k_customize_preview = "Personalizza il testo d'anteprima:",
			k_join_discord = "Unisciti al ",
			k_discord_msg = "Puoi segnalare bugs e trovare giocatori con la quale giocare lì",
			k_enter_to_save = "Premi Invio per salvare",
			k_in_lobby = "Nella Lobby",
			k_connected = "Connesso al Servizio",
			k_warn_service = "AVVISO: Impossibile Trovare Servizio Multigiocatore",
			k_set_name = "Imposta il tuo nome utente nel menu principale! (Mods > Multiplayer > Configurazione)",
			k_mod_hash_warning = "I giocatori hanno mod diverse o versioni di mod diverse! Questo può causare errori!",
			k_steamodded_warning = "I giocatori hanno diverse versioni di Steamodded installate. Questo può causare ai semi di cambiare.",
			k_warning_unlock_profile = 'ATTENZIONE! Stai giocando con un profilo non totalmente sbloccato!\nSe questa partita è classificata/torneo, per favore crea un nuovo profilo e premi "Sblocca tutto" nelle impostazioni del profilo',
			k_warning_nemesis_unlock = "ATTENZIONE! Il tuo avversario sta giocando con un profilo non totalmente sbloccato!\nPer favore se questa partita è classificata/torneo AVVISALO ADESSO!",
			k_warning_no_order = "Un giocatore ha l'opzione (Abilita il Jolly \"L'ordine\") abilitata, mentre l'altro no. Questo renderà i vostri seed diversi.",
			k_warning_cheating1 = "È probabile che il tuo avversario stia barando.",
			k_warning_cheating2 = "Se questa è una partita classificata per favore invia il messaggio '%s' in chat e poi apri un ticket in #support nel server discord",
			k_warning_banned_mods = "Uno o più giocatori stanno usando mod bandite. Queste mod non sono permesse nelle partite classificate.",
			k_message1 = "Un momento, mia madre ha scolato la pasta",
			k_message2 = "Un secondo, devo andare a spegnere il ragù",
			k_message3 = "Un momento, mi sta chiamando mamma",
			k_message4 = "Torno subito, il mio gatto sta andando a fuoco",
			k_message5 = "Aspetta, penso di aver lasciato acceso il forno",
			k_message6 = "Fermo! La mia roccia domestica è appena scappata",
			k_message7 = "Un secondo, le mie piante mi stanno chiedendo da bere",
			k_message8 = "Torno subito, i miei calzini stanno complottando contro di me",
			k_message9 = "Scusa, il mio WiFi sta avendo una crisi esistenziale",
			k_lobby_options = "Opzioni Lobby",
			k_connect_player = "Giocatori connessi:",
			k_opts_only_host = "Solo l'host della Lobby può cambiare queste opzioni",
			k_lobby_general = "Generale",
			k_lobby_gameplay = "Gameplay",
			k_lobby_modifiers = "Modificatori",
			k_lobby_advanced = "Avanzate",
			k_opts_pvp_start_round = "Il PVP inizia all'ante",
			k_opts_pvp_timer = "Timer",
			k_opts_showdown_starting_antes = "La resa dei conti inizia all'ante",
			k_opts_pvp_timer_increment = "Incremento del timer",
			k_opts_pvp_countdown_seconds = "Secondi del countdown PvP",
			k_bl_life = "Vita",
			k_bl_or = "o",
			k_bl_death = "Morte",
			k_bl_mostchips = "chi fa più punti vince",
			k_current_seed = "Seed attuale: ",
			k_random = "Casuale",
			k_standard = "Standard",
			k_sandbox = "Sandbox",
			k_sandbox_description = "Delle regole identiche a quelle Blitz,\nma qualcuno ha dato il caffè alle carte e ora si sentono loquaci.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "Le regole vanilla rimuovono tutto il contenuto Multigiocatore,\npermettendoti di giocare il gioco com'era originariamente pensato.\n\nQueste regole includono alcune modifiche Multigiocatore\ncome il timer che può essere disabilitato nelle opzioni della Lobby",
			k_blitz = "Blitz",
			k_blitz_description = 'Le regole Blitz includono carte e caratteristiche che incitano ad \nusare il tempo come una risorsa.\n\nAlcune carte sono bilanciate per adattarle al Multigiocatore:\n- "Scheda non valida" è modificata\n- "Giustizia" è rimossa\n- Le "Carte di vetro" sono modificate\n\n(Guarda la scheda dei ban e delle aggiunte/modifiche per più info)',
			k_traditional = "Tradizionale",
			k_traditional_description = 'Le regole tradizionali rimuovono le carte del Multigiocatore\nche trattano il tempo come una risorsa,\npermettendoti un gioco ancora più metodico.\n\nAlcune carte sono bilanciate per adattarle al Multigiocatore:\n- "Scheda non valida" è modificata\n- "Giustizia" è rimossa\n- Le "Carte di vetro" sono modificate\n\n(Guarda la scheda dei ban e delle aggiunte/modifiche per più info)',
			k_majorleague = "Lega Maggiore",
			k_majorleague_description = "Queste sono le regole ufficiali per la Lega Maggiore di\nBalatro Multigiocatore.\n\nQueste regole sono identiche a quelle Vanilla con alcune eccezioni:\n- L'opzione (Abilita il Jolly \"L'ordine\") è disabilitata\n- Il timer è impostato su 180 secondi\n- La prima volta che il timer arriva a 0 non perderai una vita",
			k_minorleague = "Lega Minore",
			k_minorleague_description = "Queste sono le regole ufficiali per la Lega Minore di\nBalatro Multigiocatore.\n\nQueste regole sono identiche a quelle Vanilla con alcune eccezioni:\n- L'opzione (Abilita il Jolly \"L'ordine\") è abilitata\n- Il timer è impostato su 180 secondi\n- La prima volta che il timer arriva a 0 non perderai una vita",
			k_ranked = "Classificata",
			k_ranked_description = "Queste sono le regole ufficiali per le partite classificate di\nBalatro Multigiocatore.\n\nQueste regole sono identiche a quelle  Blitz  con alcune eccezioni:\n- L'opzione (Abilita il Jolly \"L'ordine\") è abilitata\n- Devi usare la versione di Steamodded consigliata",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Delle regole settimanali progettate da @dr_monty_the_snek nel\nserver discord, che sono state aggiunte alla mod definitivamente.\n\nQueste regole bandiscono 48 Jolly, consumabili, patti, ecc...",
			k_attrition = "Logoramento",
			k_attrition_description = "Dopo il primo ante ogni buio Boss è un buio Nemesi. Non c'è tempo per prepararsi. Questa modalità ti forza ad essere pronto alla battaglia sin dall'inizio.",
			k_showdown = "Resa dei conti",
			k_showdown_description = "Dopo i primi 2 anti, ogni buio è un buio Nemesi. Questa modalità ti dà tempo di prepararti prima della battaglia.",
			k_survival = "Sopravvivenza",
			k_survival_description = "Il giocatore che batte il buio più lontano vince. Non ci sono bui nemesi. Questa modalità è un test per la tua abilità per aumentare gradualmente il record di punteggio con le mani vanilla.",
			k_weekly = "Settimanale",
			k_weekly_description = "Delle regole speciali che cambiano ad intervallo settimanale o bisettimanale. Immagino dovrai scoprire cosa fanno! Attualmente: ",
			k_smallworld = "Small World",
			k_smallworld_description = "Delle regole pesantemente sperimentali, dove 3/4 di tutto è bandito\n a caso per qualche motivo",
			k_destabilized = "Destabilizzato",
			k_oops_ex = "Aww, dang it!",
			k_asteroids = "Asteroidi",
			k_amount_short = "Qt.",
			k_filed_ex = "Archiviato!",
			k_timer = "Timer",
			k_mods_list = "Lista Mods",
			k_enemy_jokers = "Jolly della Nemesi",
			k_your_jokers = "I tuoi Jolly",
			k_nemesis_deck = "Mazzo della Nemesi",
			k_your_deck = "Il tuo mazzo",
			k_the_order_credit = "*Crediti a @MathIsFun_",
			k_the_order_integration_desc = "Questo modificherà la creazione delle carte in modo che non sia basata sull'ante ma utilizzi una singola riserva per ogni tipo/rarità",
			k_preview_credit = "*Crediti a @Fantom, @Divvy",
			k_preview_integration_desc = "Questo abiliterà l'anteprima del punteggio prima di giocare una mano",
			k_requires_restart = "*Richiede un riavvio per avere effetto",
			k_new_weekly_ruleset = "Delle nuove regole settimanali sono disponibili!",
			k_currently_colon = "Attualmente: ",
			k_sync_locally = "Sincronizza localmente (riavvia il gioco)",
			k_bans = "Ban",
			k_reworks = "Aggiunte/Modifiche",
			k_ruleset_disabled_the_order_required = '"L\'ordine" è necessario',
			k_ruleset_disabled_the_order_banned = '"L\'ordine" è bandito',
			k_ruleset_not_found = "Regole sconosciute",
			k_tutorial_not_complete = "Devi completare il tutorial prima di poter giocare il Multigiocatore",
			k_created_by = "Creato da",
			k_major_contributors = "Maggiori contribuzioni da",
			ml_enemy_loc = {
				"Posizione",
				"nemico",
			},
			ml_mp_kofi_message = {
				" ",
				" ",
				"Questa mod e server è sviluppata e mantenuta",
				"da una persona, se ti è piaciuta considera",
			},
			ml_lobby_info = {
				"Info",
				"Lobby",
			},
			loc_ready = "Pronto per il PvP",
			loc_selecting = "Selezionando un buio",
			loc_shop = "Facendo acquisti",
			loc_playing = "Giocando ",
		},
		v_dictionary = {
			a_mp_art = {
				"Disegno: #1#",
			},
			a_mp_code = {
				"Codice: #1#",
			},
			a_mp_idea = {
				"Idea: #1#",
			},
			a_mp_skips_ahead = {
				"#1# Bui Saltati Avanti",
			},
			a_mp_skips_behind = {
				"#1# Bui Saltati Indietro",
			},
			a_mp_skips_tied = {
				"Uguali",
			},
			k_banned_objs = "#1# Banditi",
			k_no_banned_objs = "Non ci sono #1# Banditi",
			k_reworked_objs = "#1# Aggiunti/Modificati",
			k_no_reworked_objs = "Non ci sono #1# Aggiunti/Modificati",
			k_ruleset_disabled_smods_version = "Versione SMODS #1# necessaria",
			k_failed_to_join_lobby = "Errore nel connettersi alla lobby: #1#",
			k_ante_number = "Ante #1#",
			k_ante_range = "Ante #1#-#2#", --Per esempio, "Ante 1-2"
			k_ante_min = "Ante #1#+", --Per esempio, "Ante 2+"
			k_credits_list = "#1# e altri ancora!", --#1# viene rimpiazzato con una lista di nomi
		},
		v_text = {
			ch_c_hanging_chad_rework = {
				"{C:attention}Scheda non valida{} è {C:dark_edition}modificata",
			},
			ch_c_glass_cards_rework = {
				"Le {C:attention}Carte di vetro{} sono {C:dark_edition}modificate",
			},
			ch_c_mp_score_instability = {
				"Il punteggio sbilanciato è {C:purple}destabilizzato{} ulteriormente:",
			},
			ch_c_mp_score_instability_EXAMPLE = {
				"  {C:inactive}(ex: {C:chips}30{C:inactive}x{C:mult}24{C:inactive} -> {C:chips}36{C:inactive}x{C:mult}18{C:inactive})",
			},
			ch_c_mp_score_instability_LOC1 = {
				"  {C:inactive}Minimo di {C:attention}1 {C:mult}Molt",
			},
			ch_c_mp_score_instability_LOC2 = {
				"  {C:inactive}Minimo di {C:attention}0 {C:chips}Fiche",
			},
			ch_c_mp_ante_scaling = {
				"{C:red}X#1#{} dimensione base del Buio",
			},
		},
		challenge_names = {
			c_mp_standard = "Standard",
			c_mp_sandbox = "Sandbox",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Torneo",
			c_mp_weekly = "Settimanale",
			c_mp_vanilla = "Vanilla",
			c_mp_misprint_deck = "Mazzo con errori di stampa",
			c_mp_legendaries = "Legendari",
			c_mp_psychosis = "Psicosi",
			c_mp_scratch = "Da zero",
			c_mp_twin_towers = "Torri gemelle",
			c_mp_in_the_red = "In rosso",
			c_mp_paper_money = "La radice di ogni male",
			c_mp_high_hand = "Mano alta",
			c_mp_chore_list = "Lista dei lavoretti",
			c_mp_oops_all_jokers = "Oops! Tutti Jolly",
			c_mp_divination = "Divinazione",
			c_mp_skip_off = "Salta tutto",
			c_mp_lets_go_gambling = "Let's go gambling!",
			c_mp_speed = "Velocità",
			c_mp_balancing_act = "Atto di bilanciamento",
		},
	},
}
