-- Localization by @blablabla_c on discord
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "KAPOT",
				text = {
					"Deze kaart is kapot of",
					"niet geïmplementeerd in de huidige versie",
					"van een mod die je gebruikt.",
				},
			},
			j_mp_defensive_joker = {
				name = "Verdedigende Joker",
				text = {
					"{C:chips}+#1#{} fiches voor elk {C:red,E:1}leven{}",
					"minder dan je {X:purple,C:white}Aartsvijand{}",
					"{C:inactive}(Momenteel {C:chips}+#2#{C:inactive} fiches)",
				},
			},
			j_mp_skip_off = {
				name = "Over-Slag",
				text = {
					"{C:blue}+#1#{} Handen en {C:red}+#2#{} weggooimogelijkheden",
					"per {C:attention}Blind{} die je meer hebt overgeslagen",
					"dan jouw {X:purple,C:white}Aartsvijand{}",
					"{C:inactive}(Momenteel {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Let's Go Gambling",
				text = {
					"{C:green}#1# in #2#{} kans om",
					"{X:mult,C:white}X#3#{} Multi en {C:money}$#4#{}",
					"{C:green}#5# in #6#{} kans om",
					"je {X:purple,C:white}Aartsvijand{} {C:money}$#7#{} te geven",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Als je een {C:attention}PvP Blind",
					"bereikt voor je {X:purple,C:white}Aartsvijand{},",
					"creëer een willekeurige {C:spectral}Spectrale{} kaart",
					"{C:inactive}(Moet ruimte voor zijn)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Siamese Joker",
				text = {
					"Tijdens een {C:attention}PvP Blind{}, krijg",
					"{X:mult,C:white}X#1#{} Multi voor elke {C:blue}Hand{}",
					"die je {X:purple,C:white}Aartsvijand{} nog over heeft",
					"{C:inactive}(Maximum {X:mult,C:white}X#2#{C:inactive} Multi, Momenteel {X:mult,C:white}X#3#{C:inactive} Multi)",
				},
			},
			j_mp_penny_pincher = {
				name = "Geldwolf",
				text = {
					"Aan het einde van een ronde, krijg {C:money}$#1#{} voor",
					"elke {C:money}$#2#{} dat je {X:purple,C:white}Aartsvijand{} heeft",
					"gespendeerd in de overeenkomstige winkel {C:attention}vorige ante{}",
					"{C:inactive}(Volgende uitbetaling: {C:money}$#3#{C:inactive})",
					-- payout = uitbetaling?
				},
			},
			j_mp_taxes = {
				name = "Belastingen",
				text = {
					"{C:mult}+#1#{} Multi voor elke kaart dat je",
					"{X:purple,C:white}Aartsvijand{} deze run {C:attention}sold{} deze run, updates",
					"wanneer de {C:attention}PvP Blind{} is geselecteerd",
					"{C:inactive}(Momenteel {C:mult}+#2#{C:inactive} Multi,",
					"{C:inactive}zal {C:mult}+#3#{C:inactive} Multi zijn)",
				},
			},
			j_mp_magnet = {
				name = "Magneet",
				text = {
					"Na {C:attention}#1#{} ronde,",
					"verkoop deze kaart om je {X:purple,C:white}Aartsvijands{}",
					"{C:attention}Joker{} met hoogste verkoopwaarde",
					"te {C:attention}kopiëren{}",
					"{C:inactive}(Momenteel {C:attention}#2#{C:inactive}/#3# rondes)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"{C:red}+#1#{} weggooimogelijkheden en",
					"{C:red}#2#{} weggooimogelijkheden voor je Aartsvijand",
					"Opgegeten na de {C:attention}PvP Blind{}",
				},
			},
			j_mp_pacifist = {
				name = "Pacifist",
				text = {
					"{X:mult,C:white}X#1#{} Multi wanneer",
					"je niet in een {C:attention}PvP Blind{} bent",
				},
			},
			j_mp_hanging_chad = {
				name = "Ongeldige Stem",
				text = {
					"Reactiveer de {C:attention}eerste{} en {C:attention}tweede{}",
					"gespeelde kaart die scoort",
					"{C:attention}#1#{} keer extra",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroïde",
				text = {
					"Verwijder #1# level van je",
					"{X:purple,C:white}Aartsvijands'{} hoogste level",
					"{C:legendary,E:1}poker hand{}",
					"aan het begin van de {C:attention}PvP Blind{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Je Aartsvijand",
				text = {
					"Neem het op tegen een andere speler,",
					"meeste fiches wint",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Spook",
				text = {
					"{C:attention}Eeuwig{} en {C:dark_edition}Negatief{}",
					"Gecreëerd en vernietigd door je {X:purple,C:white}Aartsvijand{}",
				},
			},
		},
		Enhanced = {
			m_mp_display_glass = {
				name = "Glazen Kaart",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"{C:green}#2# in #3#{} kans om",
					"kaart te vernietigen",
				},
			},
			m_mp_sandbox_display_glass = {
				name = "Glazen Kaart",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"{C:green}#2# in #3#{} kans om",
					"kaart te vernietigen",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Aartsvijand",
				text = {
					"{X:purple,C:white}#1#{}",
					"Je enige echte Aartsvijand",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Spook",
		},
		dictionary = {
			b_singleplayer = "Singleplayer",
			b_join_lobby = "Sluit je aan bij een lobby",
			b_return_lobby = "Ga terug naar lobby",
			b_reconnect = "Opnieuw verbinding maken",
			b_create_lobby = "Creëer Lobby",
			b_start_lobby = "Start Lobby",
			b_ready = "Klaar",
			b_unready = "Niet meer klaar",
			b_leave_lobby = "Verlaat de lobby",
			b_mp_discord = "Balatro Multiplayer Discord Server",
			b_start = "START",
			b_wait_for_host_start = {
				"WACHTEN OP",
				"HOST OM TE STARTEN",
			},
			b_wait_for_players = {
				"WACHTEN OP",
				"SPELERS",
			},
			b_lobby_options = "LOBBY OPTIES",
			b_copy_clipboard = "Kopieer naar klembord",
			b_view_code = "BEKIJK CODE",
			b_copy_code = "KOPIEER CODE",
			b_leave = "VERLAAT",
			b_opts_cb_money = "Geef comeback $ bij levensverlies",
			b_opts_no_gold_on_loss = "Krijg geen blind beloning na verlies van ronde",
			b_opts_death_on_loss = "Verlies een leven op non-PvP ronde verlies",
			b_opts_start_antes = "Beginnende Antes",
			b_opts_diff_seeds = "Spelers hebben verschillende seeds",
			b_opts_lives = "Levens",
			b_opts_multiplayer_jokers = "Schakel Multiplayer kaarten in",
			b_opts_player_diff_deck = "Spelers hebben verschillende Kaartspellen",
			b_opts_normal_bosses = "Schakel Blind van een baas effecten in",
			b_opts_timer = "Schakel Timer in",
			b_reset = "Reset",
			b_set_custom_seed = "Stel Aangepaste Seed In",
			b_mp_kofi_button = "mij te steunen op Ko-Fi",
			b_unstuck = "Kom los",
			b_unstuck_blind = "Vast buiten PvP",
			b_misprint_display = "Toon de volgende kaart van je Kaartspel",
			b_players = "Spelers",
			b_lobby_info = "Lobby Informatie",
			b_continue_singleplayer = "Speel verder in Singleplayer",
			b_the_order_integration = "Schakel De Orde Integratie in",
			b_view_nemesis_deck = "Toon Aartsvijands Kaartspel",
			b_toggle_jokers = "Schakel Jokers in",
			-- What's the context of toggle jokers?
			k_continue_singleplayer_tooltip = "Dit zal je huidige Singleplayer run overschrijden",
			k_enemy_score = "Huidige score van je vijand",
			k_enemy_hands = "Handen van vijand over: ",
			k_coming_soon = "Binnenkort Beschikbaar!",
			k_wait_enemy = "Wachten tot vijand is geëindigt...",
			k_wait_enemy_reach_this_blind = "Wachten tot de vijand aan deze blind geraakt...",
			k_lives = "Levens",
			k_lost_life = "Leven verloren",
			k_total_lives_lost = " Aantal Levens Verloren ($4 per stuk)",
			k_attrition_name = "Standaard",
			k_enter_lobby_code = "Voer de Lobby Code in",
			k_paste = "Plak Van Klembord",
			k_username = "Gebruikersnaam:",
			k_enter_username = "Voer gebruikersnaam in",
			k_join_discord = "Join de ",
			k_discord_msg = "Je kan daar eventuele bugs melden en kan er spelers vinden om tegen te spelen",
			k_enter_to_save = "Druk op enter om op te slaan",
			k_in_lobby = "In de lobby",
			k_connected = "Verbonden met Service",
			k_warn_service = "WAARSCHUWING: Kan de multiplayer service niet vinden",
			k_set_name = "Verander je gebruikersnaam in het hoofdmenu! (Mods > Multiplayer > Config)",
			k_mod_hash_warning = "Spelers hebben verschillende mods of mod versies! Dit kan problemen veroorzaken!",
			k_warning_unlock_profile = "Het profiel waarmee je aan het spelen bent is niet volledig vrijgespeeld. Als dit een geklasseerd spel of een spel in een toernooi is, maak een nieuw profiel aan en druk op alles vrijspelen in profiel instellingen.",
			k_warning_nemesis_unlock = "Je tegenstander is aan het spelen op een profiel dat niet volledig vrijgespeeld is. Help ze aub met een nieuw profiel aan te maken en op alles vrijspelen te drukken in profiel instellingen.",
			k_warning_no_order = "Eén speler heeft De Orde Integratie ingeschakelt terwijl de andere niet. Dit zal er voor zorgen dat de seeds verschillend zullen zijn.",
			k_warning_cheating1 = "Als je dit ziet, kan het zijn dat je tegenstander aan het valsspelen is.",
			k_warning_cheating2 = "Als dit een geklasseerd spel is, zend aub het bericht '%s' en open een support ticket in #support.",
			-- Idk if this has to be translated, because ranked games are in English
			k_message1 = "Hold on, my mom made pizza pops",
			k_message2 = "One sec, i gotta grab my slow cooker pork roast",
			k_message3 = "One moment, getting a call from my mom",
			k_message4 = "Brb, my cat is on fire",
			k_message5 = "Wait, I think I left the stove on",
			k_message6 = "Hold up, my pet rock just ran away",
			k_message7 = "One sec, my plants are asking for water",
			k_message8 = "Brb, my socks are plotting against me",
			k_message9 = "Sorry, my WiFi is having an existential crisis",
			-- Didn't translate the k_messages
			k_lobby_options = "Lobby Opties",
			k_connect_player = "Verbonden Spelers:",
			k_opts_only_host = "Enkel de Lobby Host kan deze opties veranderen",
			k_opts_gm = "Spelmodus Modificaties",
			k_opts_pvp_start_round = "PVP Start op Ante",
			k_opts_pvp_timer = "Timer",
			k_opts_showdown_starting_antes = "Showdown Start op Ante",
			k_opts_pvp_timer_increment = "Timer Toename",
			k_bl_life = "Leven",
			k_bl_or = "of",
			k_bl_death = "Dood",
			k_bl_mostchips = "Meeste fiches wint",
			k_current_seed = "Huidige seed: ",
			k_random = "Willekeurig",
			k_standard = "Standaard",
			k_standard_description = "De standaard regels, inclusief Multiplayer kaarten en veranderingen aan Balatro zelf om beter te passen binnen Multiplayer.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "De vanilla regels, geen Multiplayer kaarten, geen veranderingen aan Balatro zelf.",
			k_weekly = "Wekelijks",
			k_weekly_description = "Speciale regels die wekelijks of om de week veranderen. Je moet zelf maar uitzoeken wat het deze week doet! Momenteel: ",
			k_tournament = "Tournament",
			k_tournament_description = "De tournament regels, dit doet hetzelfde als de standaard regels maar de instellingen kunnen niet worden gewijzigd.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Origineel wekelijkse regels bedacht door @dr_monty_the_snek in de discord server die permanent aan de mod zijn toegevoegd.",
			k_attrition = "Attrition",
			k_attrition_description = "Every boss blind is a Nemesis blind. No time to prepare. This gamemode forces you to be battle-ready from the start.",
			k_showdown = "Showdown",
			k_showdown_description = "Na de eerste 2 antes, elke blind is een Aartsvijand blind. Deze spelmodus geeft je tijd om je klaar te maken voor het vechten.",
			k_survival = "Survival",
			k_survival_description = "De speler die de verste blind verslaat, wint. Geen Aartsvijand blinds. Deze spelmodus is een test van je vaardigheden om geleidelijk de hoogste score op te bouwen met Vanilla handen.",
			k_oops_ex = "Oeps!",
			k_asteroids = "Asteroïds",
			k_amount_short = "A.",
			k_filed_ex = "Gevuld!",
			-- What's the context of filled?
			k_timer = "Timer",
			k_mods_list = "Lijst van Mods",
			k_enemy_jokers = "Tegenstanders' Jokers",
			k_your_jokers = "Jouw Jokers",
			k_nemesis_deck = "Aartsvijands' Deck",
			k_your_deck = "Jouw Deck",
			k_the_order_credit = "*Credits naar @MathIsFun_",
			k_the_order_integration_desc = "Dit zal de creatie van kaarten patchen om niet gebaseerd te zijn op antes en één pool voor elk type/zeldzaamheid.",
			k_requires_restart = "*Vereist een restart om te werken",
			k_bans = "Verboden",
			k_reworks = "Toevoegingen/Herwerkingen",
			ml_enemy_loc = {
				"Locatie",
				"Tegenstander",
			},
			ml_mp_kofi_message = {
				"Deze mod en spel server is",
				"ontwikkeld en onderhouden door",
				"één persoon, als",
				"je het leuk vindt, overweeg",
			},
			ml_lobby_info = {
				"Lobby",
				"Informatie",
			},
			loc_ready = "Klaar voor PvP",
			loc_selecting = "Blind aan het selecteren",
			loc_shop = "Shoppen",
			loc_playing = "Speelt ",
		},
		v_dictionary = {
			a_mp_art = {
				"Kunst: #1#",
			},
			a_mp_code = {
				"Code: #1#",
			},
			a_mp_idea = {
				"Idee: #1#",
			},
			a_mp_skips_ahead = {
				"#1# Skips Vooruit",
			},
			a_mp_skips_behind = {
				"#1# Skips Achter",
			},
			a_mp_skips_tied = {
				"Evenveel",
			},
			k_banned_objs = "Verboden #1#",
			k_no_banned_objs = "Niet Verboden #1#",
			k_reworked_objs = "Toegevoegd/Herwerkt #1#",
			k_no_reworked_objs = "Toegevoegd/Herwerkt #1#",
		},
		v_text = {
			ch_c_hanging_chad_rework = {
				"{C:attention}Ongeldige Stem{} is {C:dark_edition}herwerkt",
			},
			ch_c_glass_cards_rework = {
				"{C:attention}Glazen Kaarten{} zijn {C:dark_edition}herwerkt",
			},
		},
		challenge_names = {
			c_mp_standard = "Standaard",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Tournament",
			c_mp_weekly = "Weekelijks",
			c_mp_vanilla = "Vanilla",
			c_mp_misprint_deck = "Foutgedrukte Deck",
			c_mp_legendaries = "Legendarische",
			c_mp_psychosis = "Psychose",
			c_mp_scratch = "Van het begin",
			c_mp_twin_towers = "Twin Towers",
			c_mp_in_the_red = "In het Rood",
			c_mp_paper_money = "Papieren Geld",
			c_mp_high_hand = "Hoge Hand",
			c_mp_chore_list = "Taken Lijst",
			c_mp_oops_all_jokers = "Oops! Enkel Jokers",
			c_mp_divination = "Waarzeggerij",
			c_mp_skip_off = "Over-Slag",
			c_mp_lets_go_gambling = "Let's Go Gambling",
			c_mp_speed = "Snelheid",
		},
	},
}
