-- Original localization by jinjoguy on Discord.
-- Futher localization by Brawmario on GitHub.
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "QUEBRADA",
				text = {
					"Está carta está quebrada ou ainda",
					"não foi implementada na versão",
					"atual de um mod que você ativou.",
				},
			},
			j_mp_defensive_joker = {
				name = "Curinga Defensivo",
				text = {
					"Este curinga ganha {C:chips}+#1#{} Fichas",
					"a cada {C:red,E:1}vida{} sua a menos",
					"do que o seu {X:purple,C:white}Rival{}",
					"{C:inactive}(No momento, {C:chips}+#2#{C:inactive} Fichas)",
				},
			},
			j_mp_skip_off = {
				name = "Amarelinha",
				text = {
					"{C:blue}+#1#{} Mão(s) e {C:red}+#2#{} Descarte(s)",
					"por cada {C:attention}Blind{} ignorado",
					"em relação ao seu {X:purple,C:white}Rival{}",
					"{C:inactive}(No momento, {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Bora Apostar",
				text = {
					"Chance de {C:green}#1# em #2#{} de",
					"{X:mult,C:white}X#3#{} Multi e {C:money}$#4#{}",
					"Chance de {C:green}#5# em #6#{} de dar",
					"ao seu {X:purple,C:white}Rival{} {C:money}$#7#{} em um {C:attention}Blind de Duelo{}",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Se você alcançar um {C:attention}Blind de Duelo{}",
					"antes do seu {X:purple,C:white}Rival{},",
					"cria uma carta {C:spectral}Espectral{} aleatória",
					"{C:inactive}(Deve ter espaço)",
				},
			},
			j_mp_conjoined_joker = {
				name = "Curinga Siamesa",
				text = {
					"Enquanto em um {C:attention}Blind de Duelo{}, este curinga",
					"ganha {X:mult,C:white}X#1#{} Multi para cada {C:blue}Mão{} que",
					"seu {X:purple,C:white}Rival{} ainda não tenha jogado",
					"{C:inactive}(Máximo de {X:mult,C:white}X#2#{C:inactive} Multi, no momento {X:mult,C:white}X#3#{C:inactive} Multi)",
				},
			},
			j_mp_penny_pincher = {
				name = "Caçador de Trocado",
				text = {
					"No fim da rodada, ganhe {C:money}$#1#{} para",
					"cada {C:money}$#2#{} que o seu {X:purple,C:white}Rival{}",
					"gastou na loja correspondente da {C:attention}última Ante{}",
					"{C:inactive}(Próximo pagamento: {C:money}$#3#{C:inactive})",
				},
			},
			j_mp_taxes = {
				name = "Impostos",
				text = {
					"Este Curinga ganha {C:mult}+#1#{} Multi para cada carta que seu",
					"{X:purple,C:white}Rival{} {C:attention}vender{} desde a última {C:attention}Blind de Duelo{},",
					"atualizando quando um {C:attention}Blind de Duelo{} for selecionado",
					"{C:inactive}(Atualmente {C:mult}+#2#{C:inactive} Multi)",
				},
			},
			j_mp_magnet = {
				name = "Imã",
				text = {
					"Ápos {C:attention}#1#{} rodadas,",
					"venda esta carta para {C:attention}Duplicar{}",
					"o {C:attention}Curinga{} do seu {X:purple,C:white}Rival{}",
					"com o maior valor de venda",
					"{C:inactive}(No momento {C:attention}#2#{C:inactive}/#3# rodadas)",
				},
			},
			j_mp_pizza = {
				name = "Pizza",
				text = {
					"Comido após uma {C:attention}Blind de Duelo{},",
					"dando {C:red}+#1#{} Descarte(s) para você",
					"e {C:red}+#2#{} Descarte(s) para seu {X:purple,C:white}Rival{},",
					"dura até o final da Ante",
				},
			},
			j_mp_pacifist = {
				name = "Pacifista",
				text = {
					"{X:mult,C:white}X#1#{} Multi enquanto não estiver",
					"em um {C:attention}Blind de Duelo{}",
				},
			},
			j_mp_hanging_chad = {
				name = "Comprovante",
				text = {
					"Reativa a {C:attention}primeira{} e a {C:attention}segunda{}",
					"carta jogada usada em pontuação",
					"{C:attention}#1#{} vez adicional",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroide",
				text = {
					"Elimina #1# nível da",
					"{C:legendary,E:1}mão de pôquer{}",
					"mais alta do seu",
					"{X:purple,C:white}Rival{} no começo de uma {C:attention}Blind de Duelo{}",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "Seu Rival",
				text = {
					"Enfrente outro jogador.",
					"Quem tiver mais fichas vence",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantasma",
				text = {
					"{C:attention}Eterno{} and {C:dark_edition}Negativo{}",
					"Criado e destruído pelo o seu {X:purple,C:white}Rival{}",
				},
			},
		},
		Enhanced = {
			m_mp_display_glass = {
				name = "Carta de Vidro",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"Chance de {C:green}#2# em #3#{} de",
					"destruir carta",
				},
			},
			m_mp_sandbox_display_glass = {
				name = "Carta de Vidro",
				text = {
					"{X:mult,C:white} X#1# {} Multi",
					"Chance de {C:green}#2# em #3#{} de",
					"destruir carta",
				},
			},
		},
		Back = {
			b_mp_cocktail = {
				name = "Baralho Coquetel",
				text = {
					"Copia todos os efeitos",
					"de {C:attention}3{} outros baralhos",
					"aleatoriamente",
				},
			},
			b_mp_gradient = {
				name = "Baralho Gradiente",
				text = {
					"Cartas também são consideradas",
					"uma classe {C:attention}acima{} ou {C:attention}abaixo",
					"para todos os efeitos de {C:attention}Curinga{}",
				},
			},
			b_mp_indigo = {
				name = "Baralho Índigo",
				text = {
					"Escolha {C:attention}1{} carta extra",
					"em Pacotes de Reforço",
				},
			},
			b_mp_orange = {
				name = "Baralho Laranja",
				text = {
					"Comece a partida com um",
					"{C:attention,T:p_mp_standard_giga}Pacote Padrão Giga{}, e",
					"{C:attention}2{} cópias de {C:tarot,T:c_hanged_man}O Enforcado",
				},
			},
			b_mp_oracle = {
				name = "Baralho Oráculo",
				text = {
					"Comece a partida com {C:spectral,T:c_medium}Médium",
					"e {C:attention,T:v_clearance_sale}Promoção",
					"Dinheiro é limitado",
					"a {C:money}$50",
				},
			},
			b_mp_violet = {
				name = "Baralho Violeta",
				text = {
					"{C:attention}+1{} Cupom na loja",
					"Durante a aposta {C:attention}1{}, Cupons",
					"são {C:attention}50%{} mais baratos",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Rival",
				text = {
					"{X:purple,C:white}#1#{}",
					"Seu único rival",
				},
			},
			p_mp_standard_giga = {
				name = "Pacote Padrão Giga",
				text = {
					"Escolha {C:attention}#1#{} de até",
					"{C:attention}#2#{C:attention} cartas{} para",
					"adicionar ao seu baralho",
					"{C:attention}Não é possível ignorar{}",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "Fantasma",
		},
		dictionary = {
			b_singleplayer = "Um jogador",
			b_join_lobby = "Entrar em uma Sala",
			b_return_lobby = "Voltar para a Sala",
			b_reconnect = "Reconectar",
			b_create_lobby = "Criar Sala",
			b_start_lobby = "Iniciar Sala",
			b_ready = "Pronto",
			b_unready = "Cancelar",
			b_leave_lobby = "Sair da Sala",
			b_mp_discord = "Servidor de Discord do Balatro Multiplayer",
			b_start = "INICIAR",
			b_wait_for_host_start = {
				"ESPERANDO PELO",
				"ANFITRIÃO COMEÇAR",
			},
			b_wait_for_players = {
				"ESPERANDO POR",
				"JOGADORES",
			},
			b_lobby_options = "OPÇÕES DA SALA",
			b_copy_clipboard = "Copiar para a área de transferência",
			b_view_code = "VER CÓDIGO",
			b_copy_code = "COPIAR CÓDIGO",
			b_leave = "SAIR",
			b_opts_cb_money = "Dar $ a cada vida perdida",
			b_opts_no_gold_on_loss = "Não ganhar recompensas de blind se perder uma rodada",
			b_opts_death_on_loss = "Perder uma vida se perder uma rodada que não for de duelo",
			b_opts_start_antes = "Antes Iniciais",
			b_opts_diff_seeds = "Todos os jogadores têm códigos diferentes",
			b_opts_lives = "Vidas",
			b_opts_multiplayer_jokers = "Habilitar cartas multijogador",
			b_opts_player_diff_deck = "Jogadores têm baralhos diferentes",
			b_opts_normal_bosses = "Habilitar efeitos de blinds de chefe",
			b_opts_timer = "Habilitar Temporizador",
			b_reset = "Reiniciar",
			b_set_custom_seed = "Personalizar Código",
			b_mp_kofi_button = "Apoie-me no Ko-fi",
			b_unstuck = "Desatravancar",
			b_unstuck_blind = "Travado Fora do Duelo",
			b_misprint_display = "Mostra a próxima carta do baralho",
			b_players = "Jogadores",
			b_lobby_info = "Informações da Sala",
			b_continue_singleplayer = "Continue no Modo Um Jogador",
			b_the_order_integration = "Habilitar integração com The Order",
			b_view_nemesis_deck = "Ver Baralho do Rival",
			b_toggle_jokers = "Alternar Curingas",
			k_continue_singleplayer_tooltip = "Isto irá sobrescrever sua partida atual no modo Um Jogador",
			k_enemy_score = "Pontuação do Inimigo",
			k_enemy_hands = "Mãos Restantes do Inimigo: ",
			k_coming_soon = "Em Breve!",
			k_wait_enemy = "Esperando o inimigo terminar...",
			k_wait_enemy_reach_this_blind = "Esperando o inimigo chegar neste blind...",
			k_lives = "Vidas",
			k_lost_life = "Perdeu uma vida",
			k_total_lives_lost = " Total de Vidas Perdidas ($4 para cada)",
			k_attrition_name = "Atrito",
			k_enter_lobby_code = "Insira o código da sala",
			k_paste = "Colar da área de transferência",
			k_username = "Nome:",
			k_enter_username = "Insira um nome",
			k_join_discord = "Entre no ",
			k_discord_msg = "Você poderá relatar erros e encontrar gente para jogar",
			k_enter_to_save = "Aperte Enter para salvar",
			k_in_lobby = "Na sala",
			k_connected = "Conectado",
			k_warn_service = "AVISO: Não foi possível encontrar o serviço Multiplayer",
			k_set_name = "Defina o seu nome de usuário no menu principal! (Mods > Multiplayer > Config)",
			k_mod_hash_warning = "Jogadores tem mods diferentes ou mods com versões diferentes! Isso pode causar problemas!",
			k_warning_unlock_profile = "O perfil em que você está jogando não está completamente desbloqueado. Se esta for uma partida ranqueada ou de torneio, por favor crie um novo perfil e aperte Desbloquear Tudo nas configurações do perfil",
			k_warning_nemesis_unlock = 'Seu oponente está jogando em um perfil que não está totalmente desbloqueado. Instrua-o a criar um novo perfil e clicar em "Desbloquear tudo" nas configurações do perfil.',
			k_warning_no_order = 'Um jogador tem a integração com "The Order" habilitada, enquanto o outro não. Isso fará com que os códigos sejam diferentes.',
			k_warning_cheating1 = "Se você está vendo essa mensagem, seu oponente pode estar trapaceando.",
			k_warning_cheating2 = "Se essa é uma partida ranqueada, por favor mande a mensagem '%s' e depois abra um ticket de suporte em #support",
			k_message1 = "Espere, minha mãe fez salgadinho de pizza",
			k_message2 = "Um segundo, preciso pegar meu assado de porco cozido lentamente",
			k_message3 = "Um momento, minha mãe está me ligando",
			k_message4 = "Já volto, meu gato está em chamas",
			k_message5 = "Espere, eu acho que deixei meu fogão ligado",
			k_message6 = "Espere, minha pedra de estimação acabou de fugir",
			k_message7 = "Um segundo, minhas plantas estão pedindo água",
			k_message8 = "Já volto, minhas meias estão tramando contra mim",
			k_message9 = "Um segundo, meu WiFi está tendo uma crise existencial",
			k_lobby_options = "Opções da Sala",
			k_connect_player = "Jogadores Conectados:",
			k_opts_only_host = "Apenas o criador da sala pode mudar estas opções",
			k_opts_gm = "Modos de Jogo",
			k_opts_pvp_start_round = "Duelo Começa no Ante",
			k_opts_pvp_timer = "Temporizador",
			k_opts_pvp_timer_increment = "Incremento do Temporizador",
			k_opts_showdown_starting_antes = "Confronto Começa no Ante",
			k_bl_life = "Vida",
			k_bl_or = "ou",
			k_bl_death = "Morte",
			k_bl_mostchips = "Mais fichas ganha",
			k_current_seed = "Código atual: ",
			k_random = "Aleatório",
			k_standard = "Padrão",
			k_standard_description = "O conjunto de regras padrão, inclui cartas Multijogador e alterações ao jogo base para se adequar ao meta Multijogador.",
			k_vanilla = "Vanilla",
			k_vanilla_description = "O conjunto de regras original, sem cartas Multijogador, sem modificações ao conteúdo do jogo base.",
			k_weekly = "Semanal",
			k_weekly_description = "Um conjunto de regras especial que muda semanalmente ou quinzenalmente. Acho que vai ter que descobrir o que é! Atualmente: ",
			k_tournament = "Torneio",
			k_tournament_description = "O conjunto de regras do torneio, é o mesmo que o conjunto de regras normal, mas não se permite alterar as opções da sala.",
			k_badlatro = "Badlatro",
			k_badlatro_description = "Um conjunto de regras semanal concebido por @dr_monty_the_snek no servidor discord que foi adicionado ao mod permanentemente.",
			k_attrition = "Atrito",
			k_attrition_description = "Todo blind de chefe é um blind de duelo.",
			k_showdown = "Confronto",
			k_showdown_description = "Depois dos dois primeiros blinds, cada blind é um blind de duelo.",
			k_survival = "Sobrevivência",
			k_survival_description = "O jogador que ganhar a blind mais avançada vence.",
			k_oops_ex = "Opa!",
			k_asteroids = "Asteroides",
			k_amount_short = "Qtd.",
			k_filed_ex = "Declarado!",
			k_timer = "Temporizador",
			k_mods_list = "Lista de Mods",
			k_enemy_jokers = "Curingas do Inimigo",
			k_your_jokers = "Seus Curingas",
			k_nemesis_deck = "Baralho do Rival",
			k_your_deck = "Seu Baralho",
			k_the_order_credit = "*Crédito ao @MathIsFun_",
			k_the_order_integration_desc = "Isto irá corrigir a criação de cartas para não ser baseada em ante e usar uma única fila para cada tipo/raridade",
			k_requires_restart = "*você precisará reiniciar o jogo para aplicar as mudanças",
			k_bans = "Banimentos",
			k_reworks = "Adições/Modificações",
			ml_enemy_loc = {
				"Localização do",
				"oponente",
			},
			ml_mp_kofi_message = {
				"Este mod e servidor de jogo é",
				"desenvolvido e mantido por",
				"uma pessoa, se",
				"gostou considere",
			},
			ml_lobby_info = {
				"Lobby",
				"Info",
			},
			loc_ready = "Pronto para Duelar",
			loc_selecting = "Escolhendo um Blind",
			loc_shop = "Comprando",
			loc_playing = "Jogando ",
		},
		v_dictionary = {
			a_mp_art = {
				"Arte: #1#",
			},
			a_mp_code = {
				"Código: #1#",
			},
			a_mp_idea = {
				"Ideia: #1#",
			},
			a_mp_skips_ahead = {
				"#1# Blinds na frente",
			},
			a_mp_skips_behind = {
				"#1# Blinds atrás",
			},
			a_mp_skips_tied = {
				"Empatado",
			},
			k_banned_objs = "#1# Banidos",
			k_no_banned_objs = "#1# Não Banidos",
			k_reworked_objs = "#1# Adicionados/Modificados",
			k_no_reworked_objs = "#1# Não Adicionados/Modificados",
		},
		v_text = {
			ch_c_hanging_chad_rework = {
				"{C:attention}Comprovante{} foi {C:dark_edition}modificado",
			},
			ch_c_glass_cards_rework = {
				"{C:attention}Cartas de Vidro{} foram {C:dark_edition}modificadas",
			},
		},
		challenge_names = {
			c_mp_standard = "Padrão",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "Torneio",
			c_mp_weekly = "Semanal",
			c_mp_vanilla = "Vanilla",
			c_mp_misprint_deck = "Baralho de Impressão Errada",
			c_mp_legendaries = "Lendários",
			c_mp_psychosis = "Psicose",
			c_mp_scratch = "Do Zero",
			c_mp_twin_towers = "Torres Gêmeas",
			c_mp_in_the_red = "No Vermelho",
			c_mp_paper_money = "Papel Moeda",
			c_mp_high_hand = "Carta Alta",
			c_mp_chore_list = "Lista de Tarefas",
			c_mp_oops_all_jokers = "Opa! Tudo Curingas",
			c_mp_divination = "Divinação",
			c_mp_skip_off = "Amarelinha",
			c_mp_lets_go_gambling = "Bora Apostar",
			c_mp_speed = "Velocidade",
		},
	},
}
