-- localization by @tavolga
return {
	descriptions = {
		Tag = {
			tag_mp_gambling_sandbox = {
				name = "赌博标签",
				text = {
					"{C:green}#1#/#2#{}几率",
					"商店会有一张免费的",
					"{C:red}稀有小丑牌{}",
				},
			},
		},
		Joker = {
			j_broken = {
				name = "错误",
				text = {
					"这张卡牌要么坏了",
					"要么在当前模组版本",
					"没有被添加。",
				},
			},
			j_mp_defensive_joker = {
				name = "防御小丑",
				text = {
					"每少于你的{X:purple,C:white}宿敌{}一条{C:red,E:1}命{}",
					"添加{C:chips}+#1#{}筹码",
					"{C:inactive}（目前{C:chips}+#2#{C:inactive}筹码）",
					"{C:inactive}（取决于当前堵住）",
				},
			},
			j_mp_skip_off = {
				name = "跳房子", -- translated to hopscotch instead of the original "skip-off" name due to the artwork
				text = {
					"每个大于你{X:purple,C:white}宿敌{}跳过{C:attention}盲注{}的次数",
					"会给予{C:blue}+#1#{}次出牌还有{C:red}+#2#{}次弃牌",
					"{C:inactive}(目前 {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive}, #5#)",
				},
			},
			j_mp_lets_go_gambling = {
				name = "咱们去赌博吧",
				text = {
					"{C:attention}PVP 盲注{}中，{C:green}#1#/#2#{}几率获得",
					"{X:mult,C:white}X#3#{}倍率和{C:money}$#4#{}。",
					"{C:green}#5#/#6#{}几率给你的",
					"{X:purple,C:white}宿敌{}{C:money}$#7#{}",
				},
			},
			j_mp_speedrun = {
				name = "速通",
				text = {
					"若你领先你的{X:purple,C:white}宿敌{}到达{C:attention}PVP盲注",
					"随机生成一张{C:spectral}幽灵牌{}",
					"{C:inactive}（必须有空位）",
				},
			},
			j_mp_conjoined_joker = {
				name = "连体小丑",
				text = {
					"在{C:attention}PVP盲注{}中，根据",
					"你的{X:purple,C:white}宿敌{}所剩余的{C:blue}出牌{}次数，每个获取",
					"{X:mult,C:white}X#1#{}倍率",
					"{C:inactive}(最高{X:mult,C:white}X#2#{C:inactive}倍率，目前{X:mult,C:white}X#3#{C:inactive}倍率)",
				},
			},
			j_mp_penny_pincher = {
				name = "吝啬鬼",
				text = {
					"回合结束时，根据你的{X:purple,C:white}宿敌{}",
					"在{C:attention}上一个底注{}相应商店",
					"花的每{C:money}$#2#{}获取{C:money}$#1#{}",
				},
			},
			j_mp_taxes = {
				name = "税款",
				text = {
					"根据你的{X:purple,C:white}宿敌{}在上一个{C:attention}PVP底注{}之后",
					"{C:attention}售出{}卡牌的次数获得{C:mult}+#1#{}倍率",
					"{C:attention}PVP底注{}选择时更新",
					"{C:inactive}（目前{C:mult}+#2#{C:inactive}倍率）",
				},
			},
			j_mp_magnet = {
				name = "磁铁",
				text = {
					"{C:attention}#1#{}回合之后，",
					"售出此卡牌即可{C:attention}复制{}",
					"你的{X:purple,C:white}宿敌{}所拥有的",
					"最高价值的{C:attention}小丑牌{}",
					"{C:inactive}（当前{C:attention}#2#{C:inactive}/#3#回合）",
				},
			},
			j_mp_pizza = {
				name = "披萨",
				text = {
					"在{C:attention}PVP盲注{}后,",
					"摧毁次小丑牌，并且在此底注提供",
					"{C:red}+#1#{} 次弃牌给你还有",
					"{C:red}+#2#{} 次弃牌给你的{X:purple,C:white}宿敌{}",
				},
			},
			j_mp_pacifist = {
				name = "和平主义者",
				text = {
					"在{C:attention}PvP盲注{}之外时",
					"{X:mult,C:white}X#1#{}倍率",
				},
			},
			j_mp_hanging_chad = {
				name = "未断选票",
				text = {
					"打出的牌中{C:attention}第一张{}和{C:attention}第二张{}",
					"记分牌额外触发{C:attention}#1#{}次",
				},
			},
			j_mp_cloud_9 = {
				name = "9霄云外",
				text = {
					"每一个回合结束时你的完整牌组内的每一张{C:attention}9{}",
					"使你获得{C:money}$1{}(最大{C:money}$4{}),然后每一张多余的{C:attention}9{}",
					"使你获得{C:money}$#1#{}",
					"{C:inactive}(当前{C:money}$#2#{}{C:inactive})",
				},
			},
			j_mp_bloodstone = {
				name = "血石",
				text = {
					"打出的{C:hearts}红桃{}花色牌",
					"在积分时有{C:green}#1#/#2#{}几率",
					"给予{X:mult,C:white}X#3#{}倍率",
					"{C:inactive}（包含实验性概率方差）{}",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "小行星",
				text = {
					"在{C:attention}PVP盲注{}开始时",
					"从你的{X:purple,C:white}宿敌{}的",
					"最高等级{C:legendary,E:1}牌型{}",
					"移除#1#个等级",
				},
			},
		},
		Blind = {
			bl_mp_nemesis = {
				name = "你的宿敌",
				text = {
					"面对另一个玩家，",
					"最多筹码获胜",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "幻影",
				text = {
					"拥有{C:attention}永恒{}和{C:dark_edition}负片{}属性",
					"由你的{X:purple,C:white}宿敌{}创建被并摧毁",
				},
			},
		},
		Enhanced = {
			m_mp_display_glass = {
				name = "玻璃牌",
				text = {
					"{X:mult,C:white}X#1#{}倍率",
					"有{C:green}#2#/#3#{}几率",
					"摧毁此牌",
				},
			},
			m_mp_sandbox_display_glass = {
				name = "玻璃牌",
				text = {
					"{X:mult,C:white}X#1#{}倍率",
					"有{C:green}#2#/#3#{}几率",
					"摧毁此牌",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "宿敌",
				text = {
					"{X:purple,C:white}#1#{}",
					"你唯一的宿敌",
				},
			},
		},
	},
	misc = {
		labels = {
			mp_phantom = "幻影",
		},
		dictionary = {
			b_singleplayer = "单人游戏",
			b_join_lobby = "加入房间",
			b_return_lobby = "回到房间",
			b_reconnect = "重新连接",
			b_create_lobby = "创建房间",
			b_start_lobby = "开始房间",
			b_ready = "准备",
			b_unready = "取消准备",
			b_leave_lobby = "退出房间",
			b_mp_discord = "Balatro Multiplayer的Discord服务器",
			b_start = "开始",
			b_wait_for_host_start = {
				"正在等待",
				"主机开始",
			},
			b_wait_for_players = {
				"正在等待",
				"玩家",
			},
			b_wait_for_guest_ready = {
				"正在等待",
				"访客",
			},
			b_lobby_options = "房间设置",
			b_copy_clipboard = "复制到剪贴板",
			b_view_code = "查看房间号",
			b_copy_code = "复制房间号",
			b_leave = "离开",
			b_opts_cb_money = "丢失生命时获取逆转金钱",
			b_opts_no_gold_on_loss = "输时不获取盲注奖励",
			b_opts_death_on_loss = "非PVP盲注输时丢失一条命",
			b_opts_start_antes = "开始底注",
			b_opts_diff_seeds = "玩家使用不同种子",
			b_opts_lives = "生命",
			b_opts_multiplayer_jokers = "启用多人游戏专属卡牌",
			b_opts_player_diff_deck = "玩家使用不同牌组",
			b_opts_normal_bosses = "启用Boss盲注效果",
			b_opts_timer = "启用计时器",
			b_reset = "重置",
			b_set_custom_seed = "设置自定义种子",
			b_mp_kofi_button = "在 Ko-fi 上支持我",
			b_unstuck = "解除卡住",
			b_unstuck_blind = "PvP 盲注之外卡住",
			b_misprint_display = "显示牌组的下一张牌",
			b_players = "玩家",
			b_lobby_info = "房间信息",
			b_continue_singleplayer = "在单机模式继续",
			b_the_order_integration = "启用 The Order 集成",
			b_view_nemesis_deck = "查看牌组",
			b_toggle_jokers = "切换小丑牌",
			b_skip_tutorial = "跳过教程",
			k_yes = "是",
			k_no = "否",
			k_has_multiplayer_content = "包含多人模式内容",
			k_forces_lobby_options = "强制房间设置",
			k_forces_gamemode = "强制玩法",
			k_values_are_modifiable = "* 指数可更改",
			k_rulesets = "规则集",
			k_gamemodes = "玩法",
			k_competitive = "竞技",
			k_other = "其他",
			k_battle = "战斗",
			k_challenge = "挑战",
			k_info = "信息",
			k_continue_singleplayer_tooltip = "这会覆盖你目前的单人模式的游戏",
			k_enemy_score = "敌方目前分数",
			k_enemy_hands = "地方剩余出牌: ",
			k_coming_soon = "即将推出!",
			k_wait_enemy = "正在等待敌方完成...",
			k_wait_enemy_reach_this_blind = "正在等待敌方到达目前盲注...",
			k_lives = "生命",
			k_lost_life = "丢失了一条命",
			k_total_lives_lost = "总共丢失生命 (每条命值$4)",
			k_attrition_name = "消耗战",
			k_enter_lobby_code = "输入房间号",
			k_paste = "从剪贴板粘贴",
			k_username = "用户名:",
			k_enter_username = "输入用户名",
			k_join_discord = "加入 ",
			k_discord_msg = "你可以在那里报告错误以及寻找其他玩家游玩",
			k_enter_to_save = "按下回车即可保存",
			k_in_lobby = "处于房间",
			k_connected = "已连接到服务",
			k_warn_service = "警告: 无法找到多人游戏服务",
			k_set_name = "请在主菜单设置用户名！ (模组 > Multiplayer > 配置)",
			k_mod_hash_warning = "玩家拥有不一致的模组或版本! 这可能会产生错误!",
			k_steamodded_warning = "玩家安装了不同版本的 Steamodded. 这坑能会导致种子不一致.",
			k_warning_unlock_profile = "你当前使用的账号尚未完全解锁。若处于排名赛或锦标赛，请创建新账号并在账号设置中选择“解锁全部”",
			k_warning_nemesis_unlock = "你的对手当前使用的账号尚未完全解锁。请指示他们去创建新账号并在账号设置中选择“解锁全部”",
			k_warning_no_order = "其中一位玩家开启了 The Order 集成，但另外一位没有开启。这会导致游戏种子不一致",
			k_warning_cheating1 = "如果你可以看见这个，你的对手可能在作弊.",
			k_warning_cheating2 = "如果这是一场排名赛, 请发送消息 '%s' 并且在 #support 频道中提交一个支持工单",
			k_message1 = "等一下，我妈做了点披萨球",
			k_message2 = "等一下，我得去拿我的慢炖烤猪肉",
			k_message3 = "稍等一下，我妈在给我打电话",
			k_message4 = "等等，我猫突然着火了",
			k_message5 = "哎哟，等一下，我好像炉子忘关了",
			k_message6 = "啊等等，我的宠物石头突然跑掉了",
			k_message7 = "稍等，我的植物在管我要水",
			k_message8 = "等等，我在被我的袜子暗中算计",
			k_message9 = "不好意思，我的网好像在经历一场存在危机",
			k_lobby_options = "房间设置",
			k_connect_player = "已连接玩家:",
			k_opts_only_host = "只有主机才能更改此设置",
			k_opts_gm = "玩法修改",
			k_opts_pvp_start_round = "PVP 开始底注",
			k_opts_pvp_timer = "计时器",
			k_opts_showdown_starting_antes = "最终对决开始底注",
			k_opts_pvp_timer_increment = "计时器增量",
			k_opts_pvp_countdown_seconds = "PVP 倒计时秒数",
			k_bl_life = "生命",
			k_bl_or = "或",
			k_bl_death = "死亡",
			k_bl_mostchips = "最多筹码获胜",
			k_current_seed = "目前种子: ",
			k_random = "随机",
			k_standard = "标准",
			k_sandbox = "的沙盒",
			k_sandbox_description = "类似于经典模式，但是有人给牌喝了点咖啡，令它们变得好像有点话多。",
			k_vanilla = "原味香草",
			k_vanilla_description = "此规则集移除了所有多人游戏内容，使您能够以游戏最初设计的方式进行游玩。\n\n此规则集仍包含多人游戏功能，如计时器。\n\n（可在房间设置中禁用）",
			k_blitz = "闪电赛",
			k_blitz_description = "本规则集包含鼓励快速游戏和将时间作为资源使用的卡牌和功能。\n\n部分卡牌在本规则集中经过调整以更好地适应多人游戏环境：\n- 未断选票 经过调整\n- 正义 被移除\n- 玻璃牌 经过调整\n\n(请参阅禁用和修改区域以获取更多信息)",
			k_traditional = "经典",
			k_traditional_description = "此规则集移除了多人游戏中以时间作为资源的各项功能。\n\n该规则集允许您畅玩多人游戏内容，同时仍能保持游戏的策略性。\n\n部分卡牌在本规则集中经过调整以更好地适应多人游戏环境：\n- 未断选票 经过调整\n- 正义 被移除\n- 玻璃牌 经过调整\n\n(请参阅禁用和修改区域以获取更多信息)",
			k_majorleague = "Major League",
			k_majorleague_description = "这是Major League Balatro的官方规则集。\n\n本规则集与原味香草规则集基本相同，但有以下几点例外：\n- 必须禁用 The Order 集成 功能\n- 计时器设置为180秒\n- 计时器首次归零时，不会失去生命",
			k_minorleague = "Minor League",
			k_minorleague_description = "这是Major League Balatro的官方规则集。\n\n本规则集与原味香草规则集基本相同，但有以下几点例外：\n- 必须启用 The Order 集成 功能\n- 计时器设置为180秒\n- 计时器首次归零时，不会失去生命",
			k_ranked = "排名赛",
			k_ranked_description = "这是 Balatro Multiplayer 模组 排名赛的官方规则集。\n\n本规则集与闪电赛规则集基本相同，但有以下几点例外：\n- 必须启用 The Order 集成 功能\n- 必须使用推荐的Steamodded版本",
			k_badlatro = "Badlatro",
			k_badlatro_description = "由@dr_monty_the_snek在Discord服务器上设计的每周规则集，现已永久添加到模组中。\n\n该规则集禁止使用48张小丑牌、消耗牌、标签等。",
			k_attrition = "消耗战",
			k_attrition_description = "第一底注后，每个Boss盲注都是宿敌盲注。你没有任何时间准备。此玩法迫使你从开局就开始备战",
			k_showdown = "决战",
			k_showdown_description = "前两个底注之后，每个盲注都是宿敌盲注。次玩法会给你充足备战的时间",
			k_survival = "生存",
			k_survival_description = "击败最远的盲注的玩家获胜。 无宿敌盲注. 此玩法会考研你逐步构建出最高分经典牌型的能力",
			k_weekly = "Weekly",
			k_weekly_description = "一个每周或每两周就会更新一次的特殊规则集。我想你就得自己去发现它到底是什么~ \n目前：",
			k_weekly_smallworld = "小世界",
			k_oops_ex = "没有！",
			k_asteroids = "小行星",
			k_amount_short = "数量",
			k_filed_ex = "已申报！",
			k_timer = "计时器",
			k_mods_list = "模组列表",
			k_enemy_jokers = "敌方小丑牌",
			k_your_jokers = "你的小丑牌",
			k_nemesis_deck = "敌方牌组",
			k_your_deck = "你的牌组",
			k_the_order_credit = "*感谢 @MathIsFun_",
			k_the_order_integration_desc = "此修复会令牌制造过程不受底注影响，以及导致每一个稀有度或类型都使用同样聚合",
			k_requires_restart = "*重启生效",
			k_new_weekly_ruleset = "新的每周规则集已被推出！",
			k_currently_colon = "目前: ",
			k_sync_locally = "本地同步（会重启游戏）",
			k_bans = "禁用",
			k_reworks = "修改",
			k_ruleset_disabled_the_order_required = "需要 The Order",
			k_ruleset_disabled_the_order_banned = "禁用 The Order",
			k_ruleset_not_found = "未知规则集",
			k_tutorial_not_complete = "你必须完成教程之后才能进行多人游戏",
			k_created_by = "创作者：",
			k_major_contributors = "主要贡献由：",
			ml_enemy_loc = {
				"敌方",
				"地点",
			},
			ml_mp_kofi_message = {
				"次模组以及游戏服务器",
				"由一个人开发并维护",
				"如果您喜欢，请考虑",
			},
			ml_lobby_info = {
				"房间",
				"信息",
			},
			loc_ready = "准备对战",
			loc_selecting = "选择盲注中",
			loc_shop = "购物中",
			loc_playing = "战斗", -- translates to "fighting" because the direct translation for playing sounds a bit funny in context
		},
		v_dictionary = {
			a_mp_art = {
				"Art: #1#",
			},
			a_mp_code = {
				"Code: #1#",
			},
			a_mp_idea = {
				"Idea: #1#",
			},
			a_mp_skips_ahead = {
				"领先#1#次跳过盲住",
			},
			a_mp_skips_behind = {
				"落后#1#次跳过盲注",
			},
			a_mp_skips_tied = {
				"跳过盲注次数相等",
			},
			k_banned_objs = "禁用 #1#",
			k_no_banned_objs = "非禁用 #1#",
			k_reworked_objs = "修改 #1#",
			k_no_reworked_objs = "非修改 #1#",
			k_ruleset_disabled_smods_version = "需求 SMODS 版本 #1#",
			k_failed_to_join_lobby = "加入房间失败: #1#",
			k_ante_number = "底注 #1#",
			k_ante_range = "底注 #1#-#2#", -- For example, "Ante 1-2"
			k_ante_min = "底注 #1#+", -- For example, "Ante 2+"
			k_credits_list = "#1# 以及更多的人!", -- #1# gets replaced with a list of names
		},
		v_text = {
			ch_c_hanging_chad_rework = {
				"{C:attention}未断选票{}有{C:dark_edition}修改",
			},
			ch_c_glass_cards_rework = {
				"{C:attention}玻璃牌{}有{C:dark_edition}修改",
			},
		},
		challenge_names = {
			c_mp_standard = "标准",
			c_mp_sandbox = "沙盒",
			c_mp_badlatro = "Badlatro",
			c_mp_tournament = "竞赛",
			c_mp_weekly = "每周挑战",
			c_mp_vanilla = "香草",
			c_mp_misprint_deck = "印错牌组",
			c_mp_legendaries = "传奇小丑",
			c_mp_psychosis = "精神分裂", -- technically translates to "schizophrenia", but the accurate term for psychosis is also used as an insult
			c_mp_scratch = "从零开始", -- translates "starting from zero"
			c_mp_twin_towers = "双子塔",
			c_mp_in_the_red = "陷入亏损", -- kind of translates to "stuck in debt"
			c_mp_paper_money = "纸币", -- don't know the context for this one, for some reason it doesnt show up in the challenges list, so this one's just a direct translation
			c_mp_high_hand = "大牌手", -- roughly translates to "big card hands"
			c_mp_chore_list = "家务表",
			c_mp_oops_all_jokers = "全是小丑牌", -- i don't think there's an equivalent for the "oops, all XXX" phrase, so here's just a direct translation of "all jokers"
			c_mp_divination = "占卜",
			c_mp_skip_off = "跳房子", -- same as translation for skip-off joker (just translates to "hopscotch")
			c_mp_lets_go_gambling = "咱们去赌博吧",
			c_mp_speed = "速度",
		},
	},
}
